### ISSUE TITLE
Trouble with import on typescript project

### ISSUE THREAD

**Issue by dpnick** [calintamas/react-native-toast-message#109]
Hi everyone,
Thanks for your work, i was exactly looking for it 👍 
It works really great if i use a "normal" use case, but as soon as i want to custom it using the config prop i have some troubles (i'm using typescript) : 

1. Actually, if i try to access to the config prop on the Toast JSX component i have the following error : 
```
Type '{ config: any; ref: (ref: any) => any; }' is not assignable to type 'IntrinsicAttributes & { ref: (ref: any) => any; } & { children?: ReactNode; }'.Property 'config' does not exist on type 'IntrinsicAttributes & { ref: (ref: any) => any; } & { children?: ReactNode; }'
``` 

2. When i try to import BaseToast i have the following error : `Module` '"react-native-toast-message"' has no exported member 'BaseToast'. Did you mean to use 'import BaseToast from "react-native-toast-message"' `instead?`

My code is the following : 

```
import Toast, { BaseToast } from 'react-native-toast-message';
const toastConfig = {
  success: ({ text1, text2, ...rest }: any) => (
    <BaseToast
      {...rest}
      style={{ borderLeftColor: 'pink', backgroundColor: 'pink' }}
      text1Style={{
        fontSize: 15,
        fontWeight: 'semibold'
      }}
      text1={text1}
      text2={text2}
    />
  )
};
{...}
<Toast config={toastConfig} ref={(ref) => Toast.setRef(ref)}  />
{...}
```

For some reasons, it looks like the index.d.ts is not exporting the same things that index.js.
I'm using the 1.4.0 lib version.

Someone else have those errors too ?
Thanks for your help

**Comment by caleb-harrelson** [comment]
The typescript declarations were manually created via a pull request (the library is not written in typescript). The errors you are getting are because the declarations have not been updated for the new version’s features.

**Comment by dpnick** [comment]
Oh ok i understand, could you tell me if this is in your backlog ?
Thanks for your help and for your quick answer!

**Comment by calintamas** [comment]
Hi @dpnick, updated type declaration in [v1.4.1](https://github.com/calintamas/react-native-toast-message/releases/tag/v1.4.1). Please let me know if it works

**Comment by dpnick** [comment]
Hi @calintamas, i can now have access to config prop and BaseToast but i have another issue trying to custom with BaseToast : 
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.`

I looked at your index.d.ts and i think this problem comme from the export of BaseToast, you did it like : 
`  export const BaseToast: React.FC<BaseToastProps>`
But i think it sould be a function (just like this related issue https://github.com/facebook/react/issues/13445)

Thanks for your quick fix 👍

**Comment by caleb-harrelson** [comment]
> React.FC<BaseToastProps>

That's a typescript shortcut for "functional component that accepts props of type `BaseToastProps`", so the exported type is already a function, not an element as was the problem in the linked issue.

**Comment by dpnick** [comment]
Ok thanks, any ideas ?
@calintamas if you need my code to reproduce let me know!

**Comment by calintamas** [comment]
@dpnick yes, that would help

**Comment by dpnick** [comment]
Actually it was pretty simple (based on your example from the documentation) : 
`
import Toast, { BaseToast, BaseToastProps } from 'react-native-toast-message';

  const toastConfig = {
    success: ({ text1, text2, ...rest }: BaseToastProps) => (
      <BaseToast
        {...rest}
        style={{ borderLeftColor: 'pink' }}
        text1={text1}
        text2={text2}
      />
    )
  };

export default function App() {
      return (
         {...}
            <Toast config={toastConfig} ref={(ref) => Toast.setRef(ref)} />
         {...}
     );
}
`

**Comment by calintamas** [comment]
@dpnick try setting the config arg type to `any`, since it does not exactly represent `BaseToastProps` - it has extra keys like `position`, `type`, `hide`, `show` etc

```js
const toastConfig = {
    success: ({ text1, text2, ...rest }: any) => ()
  };
```

If you have a suggestion on how to do this better, let me know
