### ISSUE TITLE
Change toast width?

### ISSUE THREAD

**Issue by SquareAi** [calintamas/react-native-toast-message#11]
Thanks for this project!

Is there a way to modify the toast to take up the full width of the screen and not just the content?

**Comment by calintamas** [comment]
Glad you like it!

You can render any custom component for success/error toast: https://github.com/calintamas/react-native-toast-message#render-custom-components.

The internal state is passed as props to your custom component.
```js
renderSuccessToast={(internalState) => <View />}
```

**Comment by calintamas** [comment]
@SquareAi Changed the API in `v1.3.0`.

Please take a look at the new docs - [here](https://github.com/calintamas/react-native-toast-message/tree/v1.3.0). You can now render any number of custom types.
