### ISSUE TITLE
not working auto detect text direction

### ISSUE THREAD

**Issue by hossein-ghanbari** [calintamas/react-native-toast-message#110]
In the new version, a code has been added that causes the not working auto detect text direction.

src/components/base/styles.js
line 30

or provide a way for us to add just style to text1 and text2

tank you

**Comment by calintamas** [comment]
You can change any styles on the default toast using `BaseToast`
https://github.com/calintamas/react-native-toast-message#change-default-toast-style

But what exactly is wrong? Can you describe the expected output vs the actual output?

**Comment by hossein-ghanbari** [comment]
When I use the BaseToast , I have to define all the details from the beginning (like the icon and the border color) and this is not necessary. Because for example I just want to change the font size.

**Comment by calintamas** [comment]
You can customize only what you need:
```js
const toastConfig = {
  success: (props) => (
    <BaseToast
      {...props}
      text1Style={{
        fontSize: 20
      }}
    />
  )
};
```

**Comment by caleb-harrelson** [comment]
The icon, color, etc. is defined in SuccessToast, ErrorToast, and InfoToast, which are not exported, so those values must be supplied manually to BaseToast when customizing the success, error, and info types.

Exporting those default toast types would fix his issue as one could import the actual default toast and provide only style updates.

**Comment by calintamas** [comment]
Fixed by https://github.com/calintamas/react-native-toast-message/pull/225
