### ISSUE TITLE
missing automated test props in base toast components

### ISSUE THREAD

**Issue by akshitrcrm** [calintamas/react-native-toast-message#112]
Can we add testId props to the base toast UI Components?

**Comment by calintamas** [comment]
Not at this point, but thanks for the suggestion. I'll provide a way to add extra props to all primitives from `BaseToast` in the next version

**Comment by calintamas** [comment]
Added in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
