### ISSUE TITLE
onHide in Toast.hide({ onHide }) is never called

### ISSUE THREAD

**Issue by JessicaYeh** [calintamas/react-native-toast-message#116]
The TypeScript definition for the .hide function suggests there is an onHide callback function available, but if you try to use it, it is never called.

```ts
static hide(options?: {
  onHide?: () => void
}): void;
```

**Comment by calintamas** [comment]
Hi @JessicaYeh, my mistake there. I'll fix the declaration file. 

`onHide` callback has to be passed when calling `show()`, it was designed with `autoHide: true` in mind.

```js
Toast.show({ 
  text1: 'Hello',
  autoHide: true,
  onHide: () => {}
})
```
