### ISSUE TITLE
Unable to access "props" from Toast.show()

### ISSUE THREAD

**Issue by Yandamuri** [calintamas/react-native-toast-message#129]
Here is my `Toast.Show()`

       Toast.show({
		type:  'default',
		position: 'bottom',
		text1: message,
		visibilityTime: 1000,
		autoHide: true,
		topOffset: 200,
		bottomOffset: 100,
		props: { buttonName: 'View' }
	});

Here is Toast config

      const toastConfig = {
			successWithButton: ({ text1, props }) => (
				<View style={[toastContainer, {justifyContent: 'space-between'}]}>
					<View style={{flexDirection: 'row', alignItems: 'center'}}>
						<Icons name={'toastSuccess'} />
						<Text style={toastTextStyle}>{text1}</Text>
					</View>
					<TouchableOpacity onPress={} activeOpacity={1}>
						<Text style={[toastTextStyle, {textDecorationLine: 'underline'}]}>{props.buttonName}</Text>
					</TouchableOpacity>
				</View>
			)
		};

I am using props exactly a shown in the documentation. But when I try to access `props.buttonName`, it's shows nothing. seems like unable to get the props from `Toast.Show()` even though I declared.

Can you please help how to get the "props" from `Toast.show()`

**Comment by calintamas** [comment]
Hi @Yandamuri, I'll take a look, thanks!

**Comment by ArtHerasymov** [comment]
@calintamas Hi! It seems like you declared a type that is called 'successWithButton', so when calling show(), you should specify type: 'successWithButton' instead of 'default'.

**Comment by calintamas** [comment]
@Yandamuri can you check if this was indeed the issue?

thanks @ArtHerasymov, I didn't notice when I initially looked over the code above
