### ISSUE TITLE
Toast Text1 gets shortened randomly.

### ISSUE THREAD

**Issue by HridayK97** [calintamas/react-native-toast-message#130]
I can't seem to reproduce this consistently. Across different builds/versions, sometimes the text1 of the base toast style is randomly shortened and suffixed with the '...' instead of displaying fully even when there is a ton of horizontal space left in the toast.

**Comment by lokk3d** [comment]
I got the same error

**Comment by LucaCevasco** [comment]
Someone found a solution without touching node_modules?

**Comment by ChrisMarlier** [comment]
Adding width:"100%" is not working for me. Interested for a solution too.

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!

**Comment by pankaj-ch** [comment]
If anyone stumbles upon this in the future, as I did, and seeks the solution. Here's the workaround.
Set props `text1NumberOfLines` and `text2NumberOfLines` to 0 so it can ignore the ellipsis. More on that at https://reactnative.dev/docs/text#numberoflines

e.g. 
```jsx
  config: {
    success: (props) => (
      <SuccessToast
        {...props}
        text1NumberOfLines={0}
        text2NumberOfLines={0}
      />
    ),
```

@calintamas, I loved this repo :) 
Here's my 2 cents. I believe these two component props should be defaulting to 0 instead of 1.

**Comment by dexiouz** [comment]
> ```js
> SuccessToast
> ```

Thank you very mcuh. This really solved my issue.

**Comment by dexiouz** [comment]
https://github.com/calintamas/react-native-toast-message/issues/130#issuecomment-1287354861

Thank you very much. This really solved my issue.

**Comment by dexiouz** [comment]
> If anyone stumbles upon this in the future, as I did, and seeks the solution. Here's the workaround. Set props `text1NumberOfLines` and `text2NumberOfLines` to 0 so it can ignore the ellipsis. More on that at https://reactnative.dev/docs/text#numberoflines
> 
> e.g.
> 
> ```js
>   config: {
>     success: (props) => (
>       <SuccessToast
>         {...props}
>         text1NumberOfLines={0}
>         text2NumberOfLines={0}
>       />
>     ),
> ```
> 
> @calintamas, I loved this repo :) Here's my 2 cents. I believe these two component props should be defaulting to 0 instead of 1.

Thank you very much. This really solved my issue.
