### ISSUE TITLE
Info toast in iOS

### ISSUE THREAD

**Issue by khelifioussama** [calintamas/react-native-toast-message#132]
when I am using the Toast in android it  works fine , using it in iOS , in rerender I got a green Toast empty that show then expire 
any solution please ?

**Comment by calintamas** [comment]
@khelifioussama Can you provide a code sample?

Also, [here is an example repo](https://github.com/calintamas/toast-issue137), hope it helps you pinpoint the issue

**Comment by jzxchiang1** [comment]
I'm getting this same error in Android.

When I press the home or "switch apps" button, I see an empty green toast get displayed briefly.
