### ISSUE TITLE
Number of lines cannot be passed as options

### ISSUE THREAD

**Issue by laxu** [calintamas/react-native-toast-message#133]
I see that the base notification now accepts number of lines prop, but this should be something you can pass on a case by case basis for various text elements when calling `Toast.show()`.

**Comment by calintamas** [comment]
Added in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
