### ISSUE TITLE
Offset for iPhone Notch

### ISSUE THREAD

**Issue by stefanwuest** [calintamas/react-native-toast-message#134]
Current behavior:
Toasts are not hidden properly if the phone has a notch (e.g. iPhone 12)

Desired behavior:
Toast is completely hidden on all screens

Quick fix would be to change line 344 in `index.js`
```
  const range = [height * 2, -offset, -(keyboardOffset +  #keyboardHeight)];
```

![image](https://user-images.githubusercontent.com/5959858/105874813-56a5c080-5ffd-11eb-8f19-ad731858e8ab.png)

**Comment by mav10** [comment]
To put the Provider inside SafeAreaView - isn't it a fix for that?

**Comment by calintamas** [comment]
@stefanwuest Here's an [example repo](https://github.com/calintamas/toast-issue137), without a `SafeAreaView` wrapper. I only increased the `topOffset` (default is `30`) so it looks better on devices that have a notch

```js
<Toast ref={(ref) => Toast.setRef(ref)} topOffset={50} />
```

![toast-hiding](https://user-images.githubusercontent.com/9104454/106287188-2a817e00-624f-11eb-9cd8-7e89bc636b9b.gif)
