### ISSUE TITLE
Toast don't active when i call API on android !  

### ISSUE THREAD

**Issue by nnhunguet** [calintamas/react-native-toast-message#136]
![image](https://user-images.githubusercontent.com/52577080/106253414-0a9b8b80-624a-11eb-9c4d-05d0a461dd1a.png)

Can you help me? 
Toast don't active when i call API on android !

**Comment by calintamas** [comment]
try wrapping in a `call`
```js
yield call(Toast.show.bind(Toast), {
  text1: 'hello'     
});
```
