### ISSUE TITLE
Toast not open on iOS with RN 0.63.3

### ISSUE THREAD

**Issue by cristiano-linvix** [calintamas/react-native-toast-message#137]
Good morning, i call the code bellow, but not open.

`Toast.show({
      text1: 'Hello',
      text2: 'This is some something 👋'
    });`

Any idea?

**Comment by dipakupatil** [comment]
I am also not able to run it on iOS. even I integrated all necessary steps.

**Comment by cristiano-linvix** [comment]
I integrated all necessary steps too, and nothing.

**Comment by calintamas** [comment]
Here is a quick [example repo](https://github.com/calintamas/toast-issue137) I set up, so you can check if anything is missing on your side.

Using `yarn` to install packages.

```
"react": "16.13.1",
"react-native": "0.63.4",
"react-native-toast-message": "^1.4.3"
```

**Comment by cristiano-linvix** [comment]
If I use only toast in index.js without rendering the rest of my app, toast works.
If I import the <App /> it doesn't work anymore.

**Comment by calintamas** [comment]
@cristiano-linvix Toast has to be alongside the other Views in the View hierarchy. If you can paste the reneder part of your App's entry point, maybe we can figure out what's wrong

**Comment by cristiano-linvix** [comment]
Render Routes.js
` return (
            <EmitenteContext.Provider value={{ data: EmitenteContextState, setData: setEmitenteContextState }}>
                <UsuarioContext.Provider value={{ data: UsuarioContextState, setData: setUsuarioContextState }}>
                    <NavigationContainer>
                        <StatusBar barStyle="dark-content" backgroundColor={CONSTS.ANDROID_STATUSBAR_COLOR} />
                        <MainNavigator />
                    </NavigationContainer>
                </UsuarioContext.Provider>
            </EmitenteContext.Provider>
        );`
        
Render Main index.js
` if (isHeadless) {
        // App has been launched in the background by iOS, ignore
        return null;
    }
    return (
        <>
            <Toast ref={(ref) => Toast.setRef(ref)} topOffset={50} />
            <App />
        </>
    );`

**Comment by calintamas** [comment]
@cristiano-linvix try adding it inside the `NavigationContainer`

```js
return (
    <EmitenteContext.Provider
      value={{ data: EmitenteContextState, setData: setEmitenteContextState }}>
      <UsuarioContext.Provider
        value={{ data: UsuarioContextState, setData: setUsuarioContextState }}>
        <NavigationContainer>
          <StatusBar
            barStyle='dark-content'
            backgroundColor={CONSTS.ANDROID_STATUSBAR_COLOR}
          />
          <MainNavigator />
          <Toast ref={(ref) => Toast.setRef(ref)} topOffset={50} />
        </NavigationContainer>
      </UsuarioContext.Provider>
    </EmitenteContext.Provider>
  );
```

**Comment by cristiano-linvix** [comment]
Amazing!
Thank you very much!!
Working perfectly.
