### ISSUE TITLE
Not working on web (expo-web)

### ISSUE THREAD

**Issue by johannb75** [calintamas/react-native-toast-message#138]
Hi @calintamas ,
Awesome library. It's working perfectly on IOS & Android, but I get this error on the web:
> TypeError: Cannot read property 'style' of undefined

I followed the guidelines and like I said everything is working on IOS & Android. 
I don't think the error is coming from my side but from the library.
I hope you'll find a way to fix it
Thanks in advance

**Comment by calintamas** [comment]
Hi @johannb75, it might be related to #117. I haven't got the chance to fix it yet

**Comment by johannb75** [comment]
Have you managed to fix it ?

**Comment by calintamas** [comment]
@johannb75 published a fix in v1.4.5

**Comment by johannb75** [comment]
Hi @calintamas !
It's working great everywhere. But when loading the app on IOS, I get this warning:
> Warning: Failed prop type: Invalid prop `style` supplied to `Icon`.

**Comment by calintamas** [comment]
fixed here #151
