### ISSUE TITLE
Unable to resolve module ./src on IOS when using Typescript

### ISSUE THREAD

**Issue by Franky238** [calintamas/react-native-toast-message#14]
![image](https://user-images.githubusercontent.com/3315390/79621897-62cb2c00-8115-11ea-8a45-08fccc57e8c2.png)

**Comment by Franky238** [comment]
Found an issue because i am using typescript it is expecting ts or tsx file but you have jsx as default index. you should add direct path ./src/index for fix this issue or add d.ts file also for typescript support

**Comment by calintamas** [comment]
Hi, can you open a PR to fix this?

I'm caught up with work right now - I won't be able to take a look anytime earlier than next week

**Comment by Franky238** [comment]
My solution does not work :( still have no clue why this is happening. But looks like when you are running js version of react-native everything works fine. Wierd.

**Comment by jpaas** [comment]
I worked around it by adding `jsx` to my `resolver.sourceExts` in my `metro.config.js`

**Comment by calintamas** [comment]
@Franky238 @jpaas fixed by #23 

released in `v1.3.1`
