### ISSUE TITLE
Adding global onShow 

### ISSUE THREAD

**Issue by brhoomjs** [calintamas/react-native-toast-message#143]
I want to execute haptic feedback any time `show()` function called. I tried to achieve that but its not working.

```
const toastConfig = {
  error: () => <BaseToast onShow={() => console.log("Showed")} />, // <-- Here 

};
    <>
     ...
      <Toast
        config={toastConfig}
        onShow={() => console.log("Showed")} /> // <-- And Here 
        topOffset={100}
        ref={(ref): void => Toast.setRef(ref)}
      />
    </>
```

**Comment by calintamas** [comment]
Added in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
