### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by AmmarMohamadIsmaeel** [calintamas/react-native-toast-message#153]
How could I change the direction of the toast to right to left?
I tried changing the style in the BaseToast but it did not work. Thank you

**Comment by calintamas** [comment]
Hi, are you setting RTL true?

```js
I18nManager.allowRTL(true);
I18nManager.forceRTL(true);
```

![Simulator Screen Shot - iPhone 11 Pro - 2021-02-25 at 16 50 56](https://user-images.githubusercontent.com/9104454/109170886-def8bc00-7789-11eb-89d1-e9fd0f0355b0.png)

**Comment by AmmarMohamadIsmaeel** [comment]
Yes, It worked well, Thank you so much @calintamas
