### ISSUE TITLE
Disable OnPress / Gestures

### ISSUE THREAD

**Issue by brandrewsATG** [calintamas/react-native-toast-message#154]
Hello,

Is there anyway to disable the onpress / gesture that swipes the toast away?  I'm using a custom toast if that makes any difference.

Thanks in advance for your response!

**Comment by calintamas** [comment]
Hi, `onPress` does nothing by default. As for the swipe gesture, not possible to disable it at this point

**Comment by brandrewsATG** [comment]
Thanks for your reply!

**Comment by tientran0019** [comment]
@brandrewsATG You can use this fork version to disable the swipe gesture:
[https://github.com/tientran0019/react-native-toast-message](https://github.com/tientran0019/react-native-toast-message)

**Comment by brandrewsATG** [comment]
> @brandrewsATG You can use this fork version to disable the swipe gesture:
> https://github.com/tientran0019/react-native-toast-message

Wow!  Thanks @tientran0019 !

**Comment by RWOverdijk** [comment]
👋 Has this feature been implemented? Or do I still have to use the fork for that?

**Comment by siddharth-kt** [comment]
> 👋 Has this feature been implemented? Or do I still have to use the fork for that?

Hi @calintamas, same question. (is this feature implemented.)

**Comment by calintamas** [comment]
Hey, unfortunately, not yet. I'll try in the next couple of days, or the latest during the weekend

**Comment by stepas-dev** [comment]
this would be nice to have

**Comment by MagicAce1988** [comment]
I have a great solution that I figured out for my app as I needed for example for the toast message to not be dismissable when user is offline and app shows a notification about user being offline:

Wherever you have your Toast instance in your app surround it with a view like this:


```
<View
       style={{width, height, position: 'absolute', pointerEvents: canInteract ? 'box-none' : 'none' }}>
        <Toast config={toastConfig} ref={ref => Toast.setRef(ref)} />
      </Box>
```

Then `canInteract `can be a piece of state at app level that you can change depending if you want the notification to be dismissable or not.

**Comment by Goowwy** [comment]
> Option to disable swipe gestures #446

have news? or still nothing?

**Comment by Goowwy** [comment]
> https://github.com/tientran0019/react-native-toast-message

this fork doesn't have disable swipe

**Comment by knightmate** [comment]
@wouterds is this Feature Implemented?
Can i pick this up?

**Comment by calintamas** [comment]
@knightmate Thanks for the initiative! It was implemented in #446 by @wouterds, but some tests are failing and need to be updated. I was actually going through the PR yesterday. I plan on updating the tests and merge it very soon. I'll write here once it's done.

However, if you want to pick any _other_ open issue, please feel free to do so. Just write on the issue thread, so I know what you plan to fix.

**Comment by knightmate** [comment]
Thank you for your feedback, @calintamas. I will be actively following up on this feature and staying in the loop! Additionally, I plan to explore and contribute to open issues. I'll comment on the issues once I pick up any or if I need help understanding the problem statement.

**Comment by calintamas** [comment]
Added in [2.2.0](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.2.0)
