### ISSUE TITLE
Bottom type toast have massive gap with Keyboard

### ISSUE THREAD

**Issue by giovankabisano** [calintamas/react-native-toast-message#155]
I have a simple Login use case inside my app and I want to use your Toast library within this project. My designer have a design system for our app that requires Toast to show on the bottom of the screen. 

This library able to show Bottom Toast flawlessly with no keyboard show-up
![image](https://user-images.githubusercontent.com/37267184/109442407-b82cd500-7a6a-11eb-8c12-3a6576684466.png)

But when the keyboard still showing on the screen, then the bottom toast leaves a gap above the keyboard. 
![image](https://user-images.githubusercontent.com/37267184/109442459-ea3e3700-7a6a-11eb-9700-d43edcd1cb81.png)

My expectation is to show Bottom Toast above the keyboard without having that much gap. See last image inside `What have I tried` session, that's the expectation on what should happened according to the designer, but I assume that the workaround just hackish (?)

### Implementation
```
App.js

export default function App() {
  ...

  return (
    <ApolloProvider client={defaultApolloClient}>
      <StateMachineProvider>
        <PaperProvider theme={theme}>
          <Routes />
          <Toast position="bottom" ref={(ref) => Toast.setRef(ref)} />
        </PaperProvider>
      </StateMachineProvider>
    </ApolloProvider>
  };
}
```

```
Login.js

import Toast from "react-native-toast-message";

function index(){
   ...
   Toast.show({
       text1: 'Wrong username or password',
       type: "error"
    })
   ...
}
```

### Version
- React Native:  0.63.3
- Emulator: Pixel 3a, API 29

### What have I tried?
- I try using real device (Samsung J6) but the problem still exists.
- I add `keyboardOffset={-250}` to decrease the gap between toast and keyboard, but that's **not a viable option** because **different phone have different keyboard size**.
![image](https://user-images.githubusercontent.com/37267184/109443145-61c09600-7a6c-11eb-8ccb-0eeb07221e43.png)

Are there anything that I miss in the configuration to solve this problem? Any help will be appreciated

**Comment by calintamas** [comment]
Hi @giovankabisano, this looks like a bug. Thanks for raising the issue, I'll take a look as soon as I can

**Comment by calintamas** [comment]
@giovankabisano published a fix in `v1.4.9`

**Comment by giovankabisano** [comment]
Cool! Thanks man, I'll try to upgrade my library version

**Comment by anisfrontmen** [comment]
@calintamas based on your fix commit , you remove keyboard listener for Android, that lead to another issue when the keyboard is open, the Toast stay behind the keyboard in Android.

**Comment by calintamas** [comment]
@anisfrontmen is your `android:windowSoftInputMode` set to `adjustResize`?

**Comment by anisfrontmen** [comment]
no it is set as `adjustPan` for other reasons, I do understand that it works when you change it to `adjustResize`, but it will be good to not rely on the `windowSoftInputMode` so `KeyboardAvoidView` will be the optimal solution.

**Comment by puuuudding** [comment]
@calintamas hi, I also have encountered this issue. After install the latest version, this problem is solved on Android, but it still exists on iOS, do you have a plan to check this? Thank you!

https://user-images.githubusercontent.com/8097548/112793657-3c896c80-9098-11eb-9632-44d8a47caeae.mov

**Comment by goleary** [comment]
I've seen the same on iOS where the toast shows above where the keyboard was even if the toast is shown after `Keyboard.hide()` has been called.

If I use `setTimeout(showToast, 1000)` the toast shows in the desired location, but that is quite the delay.

**Comment by cutenesss** [comment]
@puuuudding you have any workaround for this? im facing this too

**Comment by puuuudding** [comment]
@cutenesss unfortunately nothing right now

**Comment by finnmerlett** [comment]
This really needs a configuration option to switch on and off, since if you have pan-avoiding-view switched off in your android app, you need that keyboard avoiding behaviour implemented by this package...
