### ISSUE TITLE
Display Toast on the top of the Modal gives TypeError: null is not an object (evaluating 'Toast._ref.show')

### ISSUE THREAD

**Issue by t-mohsin** [calintamas/react-native-toast-message#164]
Hey - I am using the bottom sheets and have to display a toast on the top of it.

Someone in old issues has mentioned rendering Toast inside the modal. If I render the Toast inside the modal & have one in App.js it gives an error **TypeError: null is not an object (evaluating 'Toast._ref.show')**

Is there a way to bring the Toast on top of every other modal? ensuring it works perfectly on the rest of the screens.

Thanks in advance.

**Comment by calintamas** [comment]
Hi @t-mohsin, what you could to is have 2 separate Toast instances: one inside the Modal ("modal toast") and a normal one outside.

For the one outside, set the ref on the Toast object (like usual)
```js
<Toast ref={ref => Toast.setRef(ref) />
```

As for the outside one, use another ref
```js
const modalToastRef = React.useRef();

return (
  <Modal>
    <Toast ref={modalToastRef} />
  </Modal>
)
```
Then, when you want to show the "modal toast", call it using `modalToastRef.current.show()`

**Comment by t-mohsin** [comment]
@calintamas - Thanks a lot. This resolved my issue.

**Comment by Seanmclem** [comment]
I still experience this issue, seemingly when I try to use the Toast.show() in the same place I drop the original component and ref

**Comment by prox2** [comment]
same here also, when i wrap whole app components

**Comment by parthkanani93** [comment]
thanks @berk9595  its working
