### ISSUE TITLE
Toast is not appearing in TS

### ISSUE THREAD

**Issue by pawanpyakurel** [calintamas/react-native-toast-message#168]
my code: 

useEffect(() => {
    Toast.show({
      type: 'success',
      text1: 'dsffd',
      text2: 'sdfafd',
      position: 'top',
    });
  }, ]);

at app.ts:

export const App: React.FC = () => {
  return (
    <ApolloProvider client={client}>
      <StatusBar hidden={true} />
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <StatusBar hidden={true} backgroundColor={Colors.background} />
          <Toast ref={(ref: any) => Toast.setRef(ref)} />
          <NavigationContainer>
            <AppNavigation />
          </NavigationContainer>
        </PersistGate>
      </Provider>
    </ApolloProvider>
  );
};

**Comment by calintamas** [comment]
@pawanpyakurel are you using react-navigation? And if so, are you rendering the Toast as last child in the NavigationContainer?

https://github.com/calintamas/react-native-toast-message#how-to-render-the-toast-when-using-react-navigation

**Comment by Ibcs16** [comment]
@calintamas `s suggestion did the trick ;)
