### ISSUE TITLE
[Feature] Add warn support

### ISSUE THREAD

**Issue by sayem314** [calintamas/react-native-toast-message#169]
With yellowish color style by default

**Comment by calintamas** [comment]
Hi @sayem314, thanks for your suggestion.

However, I'd like to keep the lib as lightweight as possible, so I'd rather not add a new type and icon.

But what you can do is: add your own "warn" type (with a config object), by modifying `BaseToast` styles.
Docs on how to do that, here: https://github.com/calintamas/react-native-toast-message#customize-layout
