### ISSUE TITLE
Changing Font Family

### ISSUE THREAD

**Issue by Dineshkumargits** [calintamas/react-native-toast-message#176]
I had mention fontFamily in text1Style, but its not get changed.
This is my toastConfig:
`const toastConfig = {
  success: ({ text1, text2, ...rest } : BaseToastProps) => (
    <BaseToast
      {...rest}
      style={{ borderLeftColor: 'pink' }}
      contentContainerStyle={{ paddingHorizontal: 15 }}
      text1Style={{
        color: "#d44000",
        fontFamily: 'Ubuntu-Regular'
      }}
      text1={text1}
      text2={text2}
    />
  )
  };`

**Comment by a-bugaj** [comment]
the problem still exists in the version `1.4.9`, any idea how to solve it?

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
