### ISSUE TITLE
Request: Don't force icon to be image/ Support svg Icon

### ISSUE THREAD

**Issue by Samrose-Ahmed** [calintamas/react-native-toast-message#188]
Currently if you want to extend BaseToast and use your own icon, it only accepts 'ImageSource', i.e. assumes Icon is image. But many libraries use svg icons. 

Should be able to specify svg to `leadingIcon`/`trailingIcon` in `BaseToast` (or make it agnostic, ie just accept a component as prop instead of 'source').

**Comment by nightness** [comment]
Is this also why the close button for the toasts looks horrible on a large display? It's a scaled up a font instead of using SVG? 
![Temp](https://user-images.githubusercontent.com/28668902/120130926-e9619200-c18c-11eb-99b4-e66148809cd5.PNG)

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
