### ISSUE TITLE
[Feature Request] Loading style toast?

### ISSUE THREAD

**Issue by likeSo** [calintamas/react-native-toast-message#191]
We usually need toasts when networking happens.
When Network begins, Show a toast when an `ActivityIndicator` or a Circular progress bar and an optional message;
When Network ends, close the toast;

When network response error or other messages, show a toast with success or error;
For now, this library only handled the last scene.

**Comment by calintamas** [comment]
@likeSo Thanks for your suggestion. However, I want to keep the package as lightweight as possible. This is why I have exposed the `config` prop - so any uncovered / specific use-case can be handled easily by developers using the package.

Read more here - [Customize layout](https://github.com/calintamas/react-native-toast-message#customize-layout)
