### ISSUE TITLE
Text1 not showing on Android

### ISSUE THREAD

**Issue by JakeMotta** [calintamas/react-native-toast-message#194]
Hi! Using react-native-toast-message v1.4.9, and 'text1' is not visible on Android (works fine on iOS). This was working prior, but is no longer? Can't say I changed anything w/ this since it's a pretty straightforward package, but thought I'd mention it.

Wasn't sure if this is an actual issue, or if I somehow broke something, so I didn't do a PR. Hope this is helpful to someone.

[Before](https://gyazo.com/6ed3a5045114806c90cb419f7e34f235)
[Code Fix](https://gyazo.com/6a423cf384ad67a295497cf3899672ed)
[After](https://gyazo.com/6a423cf384ad67a295497cf3899672ed)

**Comment by myoganugraha** [comment]
yes, it happen on some android phone, when you remove black colors from native android code
which is you need to set the colors by the library code

step to fix for anyone who catch this issue 
add color to text1 style

`color: colors.dustyGray`

located on node_modules/react-native-toast-message/src/components/base/styles.js

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
