### ISSUE TITLE
Allow component to be used as icons

### ISSUE THREAD

**Issue by LadislavBohm** [calintamas/react-native-toast-message#203]
Currently I have to use an ImageSourcePropType to define icons. It would nice to allow any component to be passed to BaseToast so we can use SVG or whatever to display there.

**Comment by calintamas** [comment]
@LadislavBohm thanks for your suggestion. Indeed, I'll mark it as an enhancement and provide this option in a future version

Relates to https://github.com/calintamas/react-native-toast-message/issues/188

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
