### ISSUE TITLE
Height prop does nothing?

### ISSUE THREAD

**Issue by GabeK0** [calintamas/react-native-toast-message#204]
1. Initialize a new React Native project, via `npx react-native init NewProjectNameHere`
2. Install `react-native-toast-message`, via `npm install react-native-toast-message`
3. Add a Toast, and give it a custom height `<Toast height={200} ref={ref => Toast.setRef(ref)} />`
4. Show the toast, such as with ```useEffect(() => {
    Toast.show({
      text1: 'Hi',
      text2: 'pls work',
    });
  }, []);```
5. It has the original height of `60`, not the new height defined in the height prop of `200`

Unless I'm misunderstanding how this library works, this prop is not functioning currently.

**Comment by calintamas** [comment]
Hi, @GabeK0. Actually, the `height` prop specifies an initial height for the default Toast type, before `onLayout` has the chance to resolve. 

To be honest, I think I should remove it in a future version - as it does not really provide any value.

To have different Toast types with different heights, you can [Customize the layout](https://github.com/calintamas/react-native-toast-message#customize-layout) of any `type` and the animation ranges will adjust on show.

**Comment by calintamas** [comment]
Removed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
