### ISSUE TITLE
Weird behavior on web with position = bottom

### ISSUE THREAD

**Issue by artvichi** [calintamas/react-native-toast-message#205]
I don't think it's related to `react-navigation` and appears only when position is bottom.

Toast goes under navbar and sit there for some reason (doesn't disappear) 

here is how it's setup 

```
  const toastRef = useCallback((ref) => Toast.setRef(ref), []);

  return (
    <NavigationContainer linking={linking} theme={navigationTheme}>
      <RootStack />
      <Toast config={toastConfig} ref={toastRef} />
    </NavigationContainer>
```

![image](https://user-images.githubusercontent.com/51003316/121429289-fa9c6280-c933-11eb-8a70-ecfcfb314cc3.png)

**Comment by calintamas** [comment]
Hi @artvichi, are the Views in your custom config having `position: absolute`?

**Comment by jordan-tpz** [comment]
Hi, same for me

**Comment by calintamas** [comment]
Closing as [the docs have been updated for v2](https://github.com/calintamas/react-native-toast-message/blob/main/docs/navigation-usage.md#usage-with-react-navigation). If there are any other issues, feel free to re-open

**Comment by dallasnorton** [comment]
I am still having issues with this. @artvichi did you get this working? Only when `position="bottom"`, and I do have `position: 'absolute'` on my custom config, although that doesn't matter having the default config still has this issue.

**Comment by marziolek** [comment]
@calintamas still also having that issue. Once toast is hidden = animated down it generates more scroll since it is transformed.
Basically, why we cannot use `position: fixed;` instead of `position: absolute;`?
