### ISSUE TITLE
Trying to render component with toast in modal tests: React.createElement: type is invalid...

### ISSUE THREAD

**Issue by cabelin** [calintamas/react-native-toast-message#209]
I'm not able to render in the tests a screen where the toast is in a modal

I'm using react-native-testing-library to perform the tests and the react-native-toast-message mock is done, so much so that it works for other tests where toast is global

In this case I'm getting the following error:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object
```

As if Toast wasn't a component.

Can anyone help me?

**Comment by cabelin** [comment]
I managed to solve it by defining the mock as a component, which is what the implementation really is, the code follows:
```javascript
jest.mock('react-native-toast-message', () => {
  const RealComponent = jest.requireActual('react-native-toast-message');
  const ReactInternal = require('react');
  class Toast extends ReactInternal.Component {
    static show = jest.fn();
    static hide = jest.fn();

    render() {
      return ReactInternal.createElement(
        'Toast',
        this.props,
        this.props.children,
      );
    }
  }
  Toast.propTypes = RealComponent.propTypes;
  return Toast;
});
```

In this way, the `Toast` can be rendered as a component in tests.

**Comment by vijaygojiya** [comment]
> I managed to solve it by defining the mock as a component, which is what the implementation really is, the code follows:
> 
> ```js
> jest.mock('react-native-toast-message', () => {
>   const RealComponent = jest.requireActual('react-native-toast-message');
>   const ReactInternal = require('react');
>   class Toast extends ReactInternal.Component {
>     static show = jest.fn();
>     static hide = jest.fn();
> 
>     render() {
>       return ReactInternal.createElement(
>         'Toast',
>         this.props,
>         this.props.children,
>       );
>     }
>   }
>   Toast.propTypes = RealComponent.propTypes;
>   return Toast;
> });
> ```
> 
> In this way, the `Toast` can be rendered as a component in tests.

hey @cabelin  can you help me for write mock for my component here is my code :

`// App.jsx
import React from 'react';
import { FlatList, Image, View } from 'react-native';
import Toast from 'react-native-toast-message';

import MAIN_IMAGES from '../../modules/main/assets/images';
import { passwordErrors } from '../../modules/main/src/mainConstant';
import ItemValidationError from '../itemValidationError';
import ParagraphText from '../paragraphText';
import styles from './styles';

const PopupNotification = () => {
  const renderError = (props) => {
    return <ItemValidationError {...props} />;
  };
  const toastConfig = {
    success: ({ text1 }) => (
      <View style={styles.succesContainer}>
        <Image source={MAIN_IMAGES.IC_NOTIFIVATION_RED} />
        <ParagraphText customTitleStyle={styles.notificationTextStyle}>
          {text1}
        </ParagraphText>
      </View>
    ),
    passwordValidationErrorToast: () => (
      <View style={styles.container}>
        <Image source={MAIN_IMAGES.IC_NOTIFIVATION_BELL} />
        <FlatList
          keyExtractor={(_, index) => index.toString()}
          data={passwordErrors}
          renderItem={renderError}
        />
      </View>
    ),
  };

  return <Toast config={toastConfig} />;
};

export default PopupNotification;
`

thank you !

**Comment by enlivn** [comment]
@cabelin thanks! I think you might wanna PR this in to the `docs/jest-testing.md`.
