### ISSUE TITLE
On android device toast is draggable and after drag and drop, toast does not getting hide

### ISSUE THREAD

**Issue by rajashril** [calintamas/react-native-toast-message#214]
I have followed the steps mention here https://www.npmjs.com/package/react-native-toast-message to add toast in my app.
And I have followed code to display and hide the toast automatically after 2sec. 

`Toast.show({
        text1: 'Submitted',
        type: 'success',
        visibilityTime: 2000,
        autoHide: true,
        position: 'top',
        topOffset: 10,
        onPress: () => {
          Toast.hide();
        },
 });`

But when toast displayed, it is draggable, after drag and drop it is not getting hide and `visibilityTime` is also not working in this case. This is specifically on android device.
Is there any way to remove draggable behaviour of toast?.

**Comment by gcrozariol** [comment]
For some reason, I can't even make it work on Android. iOS works just fine. However, I see getting this "Possible Unhandled Promise Rejection" error. :(

**Comment by calintamas** [comment]
Issue should be fixed in [v2](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). If not, feel free to re-open

**Comment by Dev-miniyoung** [comment]
@calintamas Is this bug fixed? It's still appearing. I'm using the 2.0.2 version

**Comment by Niltonsf** [comment]
This issue didn't seem to be resolved, I'm using the toast at the bottom, and when it hides I am still able to push it from above the screen.

**Comment by amirhosein5858** [comment]
this is a temporary fix
in `node_modules/react-native-toast-message/src/index.js`

you can comment this:
`{...this.panResponder.panHandlers}`

i will fix the issue but also disabled drag-to-close of toast

**Comment by nielsq** [comment]
this issue still exists
