### ISSUE TITLE
Hide Toast on screen/tab change.

### ISSUE THREAD

**Issue by tamir61** [calintamas/react-native-toast-message#217]
Hey, did someone tried to do that using React Navigation V5? 

I'm using the Toast as in the example 
```
import Toast from 'react-native-toast-message'
import { NavigationContainer } from '@react-navigation/native';

export default function App() {
  return (
    <NavigationContainer>
      {...}
      <Toast ref={(ref) => Toast.setRef(ref)} />
    </NavigationContainer>
  );
}
```

I'm struggling to hide the Toast when the navigation state is being changed.

**Comment by Aryk** [comment]
My guess is you are getting the default "success" toast showing up when navigating to something from bottom to the top....it's supposed to be hidden but is actually showing. 

Doesn't always happen though...but I had the same problem.

I have a workaround but it's not pretty...

```ts

      <Toast
       {...props}
        type="hidden"
        config={{hidden: () => null}}
      />
```

By default the toast is not rendered at all (even off the screen). Seems to still be working correctly for me.

**Comment by tamir61** [comment]
what I'm trying to achieve is while the Toast is visible and the user navigates to another screen the Toast will hide.

**Comment by calintamas** [comment]
@tamir61 You can use `useIsFocused` on a particular screen to know when to hide the Toast

```js
import { useIsFocused } from '@react-navigation/native';

const isFocused = useIsFocused();

React.useEffect(() => {
  if (!isFocused) {
    Toast.hide();
  }
}, [isFocused]);
```
