### ISSUE TITLE
Toast background is Transparent.

### ISSUE THREAD

**Issue by shariqahmedAsm** [calintamas/react-native-toast-message#219]
Hi,

I am able to display Toast message as expected, but the only problem is that the toast background in transparent. I tried adding styles to it, but in vain it's still transparent.

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!

**Comment by RamaITB044** [comment]
I couldn't set background according to my theme. could you guide me with this
