### ISSUE TITLE
Toast not showing over modal.

### ISSUE THREAD

**Issue by debotos** [calintamas/react-native-toast-message#236]
It seems to be a zIndex issue. It's not showing when the modal/bottom sheet is preset. Thanks.

**Comment by Isaacmeedinaa** [comment]
@debotos were you able to fix this?

**Comment by RamziBenAmmar** [comment]
This is how i fixed it :

1/ create a ref out of your navigation component.
`export const ToastRef = createRef();`

2/ keep the main reference 
`<Toast ref={(ref) => {
           ToastRef.current = ref;
            Toast.setRef(ref);
}} />`

3/add Toast component to your modal 
`import { ToastRef } from 'path';`
`<Toast ref={(ref) => Toast.setRef(ref)} />`

4/on Modal hide use main reference to reset ToastRef
`onModalHide={() => Toast.setRef(ToastRef.current)}`

**Comment by pierroo** [comment]
Could this solve the issue here #279 ?
Would it deserve to be merged somehow if it fixes it?

**Comment by BG687** [comment]
I am still experiencing this issue, and have attempted many potential workarounds w/ v2. I assume this solution worked on v1.6?
