### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by gcrozariol** [calintamas/react-native-toast-message#241]
Hi,

I came across an issue where the toast is working perfectly on iOS, however it won't show up on Android. 

Here is the log I get on Android after trying to show the toast:

<img width="397" alt="Screen Shot 2021-09-06 at 7 25 01 PM" src="https://user-images.githubusercontent.com/12538405/132263494-2acb4270-1020-4f01-b3fc-82dd02b0e76b.png">
<img width="397" alt="Screen Shot 2021-09-06 at 7 25 23 PM" src="https://user-images.githubusercontent.com/12538405/132263497-260ee47b-9ca0-4c1b-b588-e2d6ebf42883.png">

Any advices? Thanks!

**Comment by YoannBuzenet** [comment]
Hey @gcrozariol, did you find something ?

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
