### ISSUE TITLE
How to use svg files to replace the heading/trailing icons?

### ISSUE THREAD

**Issue by YangRongAtGit** [calintamas/react-native-toast-message#245]
Hello,
I am trying to use some custom icons for replacing heading/trailing icons. I have something like
```
const errIcon: ImageSourcePropType = {
  uri: '../assets/tick.svg'
};

export const toastConfig = {
  error: ({ text1, props, ...rest }) => (
    <BaseToast
      {...rest}
      leadingIcon={errIcon}
      contentContainerStyle={{ paddingHorizontal: 15 }}
      text1Style={{
        fontSize: 15,
        fontWeight: '400'
      }}
      text1={text1}
    />
  )}
```
But the icons do not show in the toast. My question is: what is the correct way to use SVG images in the toast?

**Comment by calintamas** [comment]
In `v2.0.0`, `leadingIcon`, `trailingIcon` props  were replaced with `renderLeadingIcon`, `renderTrailingIcon` to gain total control over the icon layout / behavior. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
