### ISSUE TITLE
On iOS Toast shows behind notch

### ISSUE THREAD

**Issue by Pixele9** [calintamas/react-native-toast-message#247]
I have configured the Toast as it says in the docs.
But it appears behind the notch when it is not triggered.

![image](https://user-images.githubusercontent.com/9836752/134197153-62ae0d0f-384c-4df8-b4b4-048fc0049e02.png)

Is there a way to move it further back to prevent it from displaying? Any work around?

Thanks in advance!

**Comment by younisabuzayed** [comment]
If you use nativebase and wrap Toast. this is problem. You can wrap in react navigation no problem but nativebase no.
this link you can find a solution : https://github.com/calintamas/react-native-toast-message#how-to-render-the-toast-when-using-react-navigation

**Comment by nibblesnbits** [comment]
@younisabuzayed, I've implemented the solution suggested, but it doesn't work.  I still get the toast showing outside where `SafeAreaView` would render it.

![image](https://user-images.githubusercontent.com/6042917/135541065-70e2c7da-5c20-49ea-a371-475a1dc7c422.png)

**Comment by younisabuzayed** [comment]
Can you send code when you put " <Toast ref={(ref) => Toast.setRef(ref)} />" on in your code?

**Comment by Pixele9** [comment]
In my case I solved it by moving the Toast component outside the </SafeAreaView> like this:
![image](https://user-images.githubusercontent.com/9836752/135571217-a5f4264c-5fab-4872-bf15-c0f6def55ecd.png)

**Comment by ToshKoevoets** [comment]
Also use when using on web and native, not possible to set opacity to 0 when in active? would be a lot more stable solution

**Comment by calintamas** [comment]
> Also use when using on web and native, not possible to set opacity to 0 when in active? would be a lot more stable solution; my setup is a bit more layered

@ToshKoevoets Starting with v2.0.0, opacity is indeed 0 when the Toast is not visible.


> In my case I solved it by moving the Toast component outside the SafeAreaView like this:
> ![image](https://user-images.githubusercontent.com/9836752/135571217-a5f4264c-5fab-4872-bf15-c0f6def55ecd.png)

That's exactly right, the Toast instance has to be alongside NavigationContainer. More details can be found here - [Usage with react-navigation](https://github.com/calintamas/react-native-toast-message/blob/main/docs/navigation-usage.md#usage-with-react-navigation).

I'll close the issue. If you find anything else, feel free to reopen.
