### ISSUE TITLE
Extending existing toasts breaks trailing icon press

### ISSUE THREAD

**Issue by CalebLovell** [calintamas/react-native-toast-message#250]
For some reason, when doing this:

```js
const toastConfig = {
  success: ({ ...props }: BaseToastProps) => (
    <SuccessToast {...props} text1Style={styles.text1} text2Style={styles.text2} />
  ),
};
```

The trailing icon stop works. You can no longer click the little x to close the toast. I fixed it by doing this:

```js
const toastConfig = {
  success: ({ ...props }: BaseToastProps) => (
    <SuccessToast {...props} text1Style={styles.text1} text2Style={styles.text2} onTrailingIconPress={() => Toast.hide()} />
  ),
};
```

But that doesn't seem like it should be required. I briefly looked through the source code but couldn't quite understand what was happening. But it seemed like maybe the default values for BaseToastProps were not working.

Thanks for your work on this library! It's great.

**Comment by calintamas** [comment]
In `v2.0.0`, `onTrailingIconPress` has been replaced with `renderTrailingIcon` prop to gain total control over the icon layout / behavior. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!

**Comment by NemyaNation** [comment]
@calintamas , now that we can render our own icon + touchableOpacity how can we code it so that it has the same functionality as before. i.e `Toast.hide()`
