### ISSUE TITLE
autoHide: false crashes on android

### ISSUE THREAD

**Issue by tinni95** [calintamas/react-native-toast-message#256]
Steps to reproduce : 

Create a Toast.show and add autoHide false.

The app crashes on android.
Works fine on Ios

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
