### ISSUE TITLE
Does not play nice with Modal on React Native Web

### ISSUE THREAD

**Issue by haveamission** [calintamas/react-native-toast-message#257]
When trying to use the example suggested for in-modal toasts on React Native Web, I get an empty modal that is always present (even before running Toast.show()), and when trying to actually launch a modal, the behind modal toast shows still.

**Comment by Allwithyou999** [comment]
Please use react-native-toast-notification. That works for web.

**Comment by calintamas** [comment]
Should be fixed in [v2.1.2](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.1.2), please let me know if you have any issues
