### ISSUE TITLE
When i close the toast, it goes to the bottom of screen

### ISSUE THREAD

**Issue by mixermat99** [calintamas/react-native-toast-message#258]
hi, i am using react native web with expo i have a strage issue.
when i close the toast or the toast close itsself, it goes ander the screen
 
![Capture](https://user-images.githubusercontent.com/22844724/138093748-8f13cc9f-af57-4acc-b1ca-0fea5e0d471a.PNG)

My configuration is:
![image](https://user-images.githubusercontent.com/22844724/138093884-aa642a82-294f-4ba2-88ea-39fa1795f00d.png)

**Comment by calintamas** [comment]
Fixed in `v2.0.0`. [Read the complete changelog](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.0). 

If you find any issues with the v2 implementation, feel free to reopen this issue. Thanks!
