### ISSUE TITLE
No icons for error and info

### ISSUE THREAD

**Issue by andreydos** [calintamas/react-native-toast-message#27]
Hello.
Thanks for good work! 
I have one problem. When I not specify the type of toast or set it to "success" I got a success icon on the left side of my message, but if I change the type to error/info I get an empty white area on the left side of the message text. 
Version 1.3.1 React-native version 0.62.2

**Comment by calintamas** [comment]
@andreydos I'll take a look today

**Comment by calintamas** [comment]
@andreydos everything seems to be working fine. 

```
"react-native": "0.62.2",
"react-native-toast-message": "^1.3.1"
```
