### ISSUE TITLE
After toast shown within Modal, main instance outside of Modal doesn't work anymore

### ISSUE THREAD

**Issue by jstheoriginal** [calintamas/react-native-toast-message#279]
First of all, this lib is fantastic. And v2 is great. Thank you!

**Describe the bug**
I have two `Toast` instances setup. One alongside `NavigationContainer` from `react-navigation`, and one within `Modal`.

When I show a toast outside of the modal, it shows fine. And when I show a toast inside of the Modal when it's visible, it works fine. However, when I try to show a toast again outside of the Modal, it doesn't show. Bringing up the Modal again shows the modals within the modal fine still. 

So it's almost as if it's not tracking the correct instance and only tracks the Modal instance once Modal shows a toast.

**Steps to reproduce**
1. Show a toast when a Modal is not visible.
2. Make a Modal visible.
3. Show a toast. It shows on top of the Modal.
4. Make the modal not visible anymore.
5. Show a toast. It doesn't show.
6. Make the Modal visible again. It shows on top of the Modal.

**Expected behavior**
The toasts once a modal is no longer visible should show/hide properly.

**Screenshots**
This video shows this happening with a demo screen i have.

https://user-images.githubusercontent.com/5117473/140588648-938b1a60-876e-4d99-b0ff-55400eda0319.mp4

**Code sample**
I can provide this next week if needed. It would take some time to replicate what I've done and extract to a sample project. But let me know if it's not easily reproducible with more tests.

**Environment (please complete the following information):**
 - OS: iOS, Android
 - react-native-toast-message version: v2.0.1
 - react-native version: v0.64.2

**Additional context**
Likely related, but if you try to call `Toast.hide()` (like in a close button's onPress) on a toast that was shown and still on screen when a Modal becomes visible, it doesn't hide. The close button tap doesn't work. Swiping to dismiss still works, however.

This is showing a toast being shown just before the bottom modal appears, and how it can't be dismissed using `Toast.hide()` afterwards.

https://user-images.githubusercontent.com/5117473/140588724-3b9403ac-e5c5-4204-97c7-e59ac0828da8.mp4

Possibly also related, but I noticed that if I pass `autoHide: false` via `Toast.show` for the Toast instance within the Modal (which has autoHide set to true), it still auto hides despite indicating to not.

**Comment by jstheoriginal** [comment]
Here's a demo project that works like the videos i put above! https://github.com/jstheoriginal/RNToastMessageExample

**Comment by akimabs** [comment]
still waiting for this issue was resolved

**Comment by calintamas** [comment]
@jstheoriginal Thanks for the detailed explanation. I haven't got the change to look into it yet, but I'll let you know as soon as I have.

As a side-note: when I did my testing with the [Modal](https://reactnative.dev/docs/modal) component from the react-native package, everything seemed fine.

**Comment by jstheoriginal** [comment]
Sounds good!

I did also try using the standard Modal from react native and had the same issue happen to me, fwiw.

**Comment by pierroo** [comment]
Facing the same issue; will update here if ever I find anything...
For the time being, did anyone find a solution yet?

**Comment by calintamas** [comment]
@jstheoriginal First, thank you for taking the time to create a repo, it was very helpful for reproducing the issue 🙌 

Second, I think I have a solution, published in a `v2.1.0-beta.1` version of the package, which fixes the issue (at least on my side). 

There is a change in API in this version, that needs to be done for it to work:

1. On the Toast instance that's rendered in your **app root**:
    ```js
    import Toast from 'react-native-toast-message'
    
    <Toast setRef={Toast.setRootRef} />
    ```
1. On the Toast instance that's rendered **inside a Modal**:
    ```js
    import Toast from 'react-native-toast-message'
    
    <Toast setRef={Toast.setModalRef} />
    ```
1. Now, when you want to show the Toast, everything goes as usual:
   ```js
   import Toast from 'react-native-toast-message'
   Toast.show(...)
   ```
   When the Modal is visible, the Modal ref will be used, otherwise the Root ref.

@jstheoriginal @pierroo @akimabs Please try to upgrade to this beta version and confirm if it works or not. 

```sh
yarn add react-native-toast-message@2.1.0-beta.1
```

If everything works fine for you as well, I'll prepare a stable release with the fix.

**Comment by jstheoriginal** [comment]
Tested it out and it works like a charm now! Thanks!

Two things of note:

1. autohide

For some reason, the modal instance never seems to obey the autohide value provided via the show function if setting autohide to true in the toast instance. It always automatically hides, while the root instance will correctly obey the prop's value. 

I have `autoHide={true}` set by default in the instance, and then when setting it to false via the show function, it still auto hides in the modal instance for some reason. The root instance behaves as expected, however. 

Alternatively, if I set `autoHide={false}` by default on the toast instance, and then set it to true or false via the show function, the **root** instance **never** shows, but the modal instances now work fine.

2. react-navigation native stacks

If using a native stack (ie. via `createNativeStackNavigator`) rather than a js stack (ie. `createStackNavigator`) AND using the `presentation: 'modal'` screen option to present screens in the new iOS 14+ layered presentation style for modals, these screens also require a modal instance just like anything within a `Modal` component. 

This isn't a new issue--it's just something I figured out when upgrading to v6 and migrating from js stacks to native stacks. Probably worth a note in the docs. 

To avoid needing to add an instance in screens presented modally in native stacks with that presentation type, a native stack's screen options should be set to `presentation: 'containedModal'` instead, but it will not have the newer layered modal look as of iOS 14+.

**Comment by jstheoriginal** [comment]
> ### 2. react-navigation native stacks
> If using a native stack (ie. via `createNativeStackNavigator`) rather than a js stack (ie. `createStackNavigator`) AND using the `presentation: 'modal'` screen option to present screens in the new iOS 14+ layered presentation style for modals, these screens also require a modal instance just like anything within a `Modal` component.
> 
> This isn't a new issue--it's just something I figured out when upgrading to v6 and migrating from js stacks to native stacks. Probably worth a note in the docs.
> 
> To avoid needing to add an instance in screens presented modally in native stacks with that presentation type, a native stack's screen options should be set to `presentation: 'containedModal'` instead, but it will not have the newer layered modal look as of iOS 14+.

Note: I just found out that It's also not possible to show a toast inside of a `Modal` while presenting a screen natively via the `presentation: 'modal'` type, as it'll just use the one that had the latest `setModalRef` set (both need their own instances and need to use `setModalRef`). So If you have a `Modal` inside of one of these screens, the `Modal`'s toast gets set to the modal ref first, and then the screen's toast modal ref gets set second, since React renders children before parents. 

I solved this issue locally by just adding a 3rd ref that can be used called `setModal2Ref`, with priority just going from modal 2 to modal to root, so if needed, any Modals can just use the 2nd modal ref and screens presented modally can use the first. It's an if-you-need-it type of option. I can submit a PR if you think it makes sense @calintamas!

**Comment by calintamas** [comment]
@jstheoriginal Can you please push this last demo example to your repo? I want to explore a bit how the library exposes this "setRef" API. As the nesting level increases past 3, these 3 functions will again not be enough. 

In general, maybe we can avoid having too many (different) functions, as they might cause confusion as to how they should be used.

I'm thinking of maybe having something like:
```js
 <>
  <Toast /> // Toast instance in App's Root
    <ModalA>
      <Toast level={1} /> // Toast instance inside Modal A (1 level nesting)
      <ModalB>
        <Toast level={2} /> // Toast instance inside Modal B (2 levels nesting)
          <ModalC>
            <Toast level={3} /> // Toast instance inside Modal C (3 levels nesting)
             // and so on, if needed
          </ModalC>
      </ModalB>
    </ModalA>
 </>
```

The "highest" Toast in the `View` hierarchy has the highest priority:
3 --> 2 --> 1 --> 0
And refs are handled internally.

This would also allow the developer to decide a different priority, if needed. I believe this would solve your use-case as well, but we would need to test it.

**Comment by jstheoriginal** [comment]
Yeah i think that makes sense! Will make the updated example in a bit for you to play with.

I did find an issue with my way, and it's probably not super straightforward of an issue to solve.

Since a Toast instance needs to exist in each modally-presented react-navigation native stack screen in order for toasts to not be rendered underneath when using `presentation: 'modal'`, it causes an issue when they use the same ref in this scenario:

- Show a toast in a modally-presented react-navigation screen
- Present another modally-presented react-navigation screen on top of this screen
- Show a toast (it shows fine)
- Close the top screen to return to the other modal screen underneath
- Show a toast (the toast doesn't show)
- Cause something to trigger a re-render
- Show a toast (it shows fine again)

Until a re-render of the screen happens that causes the Toast's ref to be set again after the 2nd Toast's ref was set and overrode it, the toast won't show on the initial instance.

I'm not too sure how often this would happen where a re-render doesn't happen, but it can. It could be solved by setting a level of 4 for the 2nd modally-presented screen, but I think having to manage more than 3 levels can get to be too much, especially since screens can change where they get presented from depending on context. 

It's easier to rationalize that non-modal screens use level 1 via the single root instance, modal screens use level 2 and actual Modal components use level 3. Anything past that will just become buggy, and have too much cognitive load to make sure there aren't conflicting levels across screens/modals (and probably too hard to explain in docs).

https://user-images.githubusercontent.com/5117473/143780264-3b8e915c-b46e-4927-b350-2ad8fc828def.mp4

**Comment by jstheoriginal** [comment]
@calintamas I just pushed changes that add the modal screens. the first tab runs the demo in a non-modal, and the second tab runs it inside of the first modal. the last button in the demo shows the 2nd modal screen. Hopefully this works for you.

https://github.com/jstheoriginal/RNToastMessageExample

![Simulator Screen Shot - iPhone 11 - 2021-11-28 at 12 57 07](https://user-images.githubusercontent.com/5117473/143781969-4a368d97-c436-48cd-8ac1-751d56ce4a81.png)

![Simulator Screen Shot - iPhone 11 - 2021-11-28 at 12 57 13](https://user-images.githubusercontent.com/5117473/143781970-be7d2a6e-f72c-42b0-acf8-35c01c65fdf7.png)

**Comment by calintamas** [comment]
@jstheoriginal Thank you, I'll hopefully be able to take a look tomorrow. Anyhow, as soon as I have the 2nd beta, I'll ping you here. Really appreciate your help on this!

**Comment by calintamas** [comment]
@jstheoriginal I just published `v2.1.0-beta.2`. 

Here is the commit that integrates it in your example repo: https://github.com/calintamas/RNToastMessageExample/commit/4e255791b2a8a0730dda85b07bef040719083593. Please check it out when you can and see if you find any issues. From my exploration, everything seems fine.

I've also updated the docs on the v2.1.0 branch - [How to show the Toast inside a Modal?](https://github.com/calintamas/react-native-toast-message/blob/v2.1.0/docs/modal-usage.md)

**Comment by jstheoriginal** [comment]
@calintamas Just put up this PR. Let me know what you think. https://github.com/calintamas/react-native-toast-message/pull/293

**Comment by calintamas** [comment]
> @calintamas Just put up this PR. Let me know what you think. #293

@jstheoriginal Taking a deeper look today. I like the idea of completely handling refs internally 👍
