### ISSUE TITLE
Swiping Toast up re-creates it

### ISSUE THREAD

**Issue by siddharth-kt** [calintamas/react-native-toast-message#280]
**Describe the bug**
When we swipe up the Toast(with position="top") too high without removing finger (keep swiping slowly as much high as possible, don't remove finger in between swipe), then toast re-enters from middle of the page (on android) I didn't faced this problem with position="bottom".

**Expected behavior**
It should not be recreated.

**Code sample**

// In App.js
    <Toast
      position="top"
      topOffset={60}
      onPress={() => {
        Toast.hide();
      }}
    />

// in other file.
    Toast.show({
      type: 'success',
      text1: 'Hello',
      text2: 'This is some something 👋',
    });

**Environment**
 - OS: Android
 - react-native-toast-message version: [e.g. v2.0.1]
 - react-native version [e.g. v0.65.0]

**Comment by pierroo** [comment]
I can confirm I am facing this issue as well on android; which even happens when swiping the toast up fast; (which we always do intuitively when wanting to close a toast)
it blinks back to the middle of the screen then up to its initial position; this is the last issue I am facing with this otherwise perfect toast plugin.

**Comment by calintamas** [comment]
Fixed in [v2.0.2](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.2)

**Comment by siddharth-kt** [comment]
> Fixed in [v2.0.2](https://github.com/calintamas/react-native-toast-message/releases/tag/v2.0.2)

I am sorry but its still happening. 🤔

**Comment by calintamas** [comment]
@siddharth-kt Make sure it's not some cache issue with npm / node_modules and you are indeed running v2.0.2. I can no longer reproduce the issue on my side

**Comment by siddharth-kt** [comment]
> @siddharth-kt Make sure it's not some cache issue with npm / node_modules and you are indeed running v2.0.2. I can no longer reproduce the issue on my side

Sorry my bad, its working fine now (yeah it was cache issue) thanks. 😅

**Comment by calintamas** [comment]
> Not sure if it is intentional behavior, but if I touch and hold toast, it never hides (`autoHide` is set to `true`). The hiding animation takes place, but toast stays on screen infinitely. You may need to pull your finger down a bit after the hiding animation is complete in order to display toast again. I get this behavior on iOS as well as Android. Package version: 2.1.0

Hi @danieldaukapp, I'll have to check, thanks

**Comment by lxhau** [comment]
A bug has opened on version 2.1.1. Not hide toast when show position in top.

**Comment by chetanparmar95** [comment]
I still get toast on swiping up. It still re-creates it. Version. 2.1.6

**Comment by bryanltobing** [comment]
still happening, 

it will persist and there is no way to close it

**Comment by bim-oulabi** [comment]
Still happens in ^2.2.0, when swiped up there is no way to close it unless its triggered again
