### ISSUE TITLE
Use minHeight and minWidth instead of height & width.

### ISSUE THREAD

**Issue by sangameshsomawar** [calintamas/react-native-toast-message#312]
When we set text1NumberOfLines more than 1 then the text is not visible, because height is fixed.

https://github.com/calintamas/react-native-toast-message/blob/main/src/components/BaseToast.styles.ts#L11

**Comment by calintamas** [comment]
Hi @sangameshsomawar, you can [overwrite the container styles](https://github.com/calintamas/react-native-toast-message/blob/main/src/components/BaseToast.tsx#L32) with the `style` prop on `BaseToast`. I think this covers your use-case, right?

**Comment by sangameshsomawar** [comment]
@calintamas: Thanks,  It worked.
