### ISSUE TITLE
 Error: Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by ranshine** [calintamas/react-native-toast-message#313]
I tried Custom layouts from documentation, i got this error

Error: Text strings must be rendered within a <Text> component.

```
<Toast config={toastConfig} bottomOffset={20} />;

This error is located at:
    in RNCSafeAreaView (at SafeAreaView.tsx:8)
    in SafeAreaView (at AppNavigator.tsx:101)
    in AppNavigator (at App.tsx:23)
    in ThemeProvider (at Provider.tsx:83)
    in RCTView (at View.js:32)
    in View (at PortalHost.tsx:125)
    in Portal.Host (at Provider.tsx:81)
    in Provider (at Theme.tsx:
Add any other context about the problem here.
```

**Comment by blueberrry** [comment]
Hi! I was experiencing the same issue since upgrading.

If I was passing an empty string to text1 or text2 it was erroring out.

So I changed it to this

`type ToastConfigTypes = {
      type: string;
      text1?: string;
      text2?: string;
    };
    const showToast = ({ type, text1, text2 }) => {
      let toastConfig: ToastConfigTypes = {
        type,
      };

      if (text1.length > 0) {
        toastConfig = { ...toastConfig, text1 };
      }

      if (text2.length > 0) {
        toastConfig = { ...toastConfig, text2 };
      }

      Toast.show({
        ...toastConfig,
        onHide: () => resetToast(),
      });
    };

    if (toastType === 'success' || toastType === 'info' || toastType === 'error') {
      showToast({ type: toastType, text1: toastFirstLine, text2: toastSecondLine });      
    }`

**Comment by Mirjo** [comment]
I have the same issue when calling Toast.show(...) from outside a React Component i.e from a plain TypeScript file. Moving the method call back into a React Component it works just fine

**Comment by calintamas** [comment]
> `<Toast config={toastConfig} bottomOffset={20} />;`

I think the problem here is that you have a semicolon at the end of the statement `;`

> If I was passing an empty string to text1 or text2 it was erroring out.

I'll create a fix for this use-case
