### ISSUE TITLE
Would it be possible to each toast type be positioned separately?

### ISSUE THREAD

**Issue by Hajan39** [calintamas/react-native-toast-message#320]
I need to implement two types of toast notification. The first is top notification and the second one is bottom notification. Currently, I am using two different libraries. It would be great if the current library would be able to do it.
Or do you have some workaround?

**Comment by calintamas** [comment]
Hi @Hajan39, you could always show a certain type with position: top and some other type with position: bottom

```js
const defaultOptions = {
  success: {
    type: 'success',
    position: 'top',
  },
  info: {
    type: 'info',
    position: 'bottom',
  },
}

Toast.show({
  ...defaultOptions.success,
  text1: 'Success message',
})

Toast.show({
  ...defaultOptions.info,
  text1: 'Info message',
})
```

As long as you don't need both of them visible at the same time, it should work fine.
