### ISSUE TITLE
 ERROR  Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by vivek1209codeb** [calintamas/react-native-toast-message#324]
**Describe the bug**

**Steps to reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Code sample**
To help debugging, please add a code sample that reproduces the issue.

**Environment (please complete the following information):**
 - OS: [iOS, Android, Web]
 - react-native-toast-message version: [e.g. v2.0.0]
 - react-native version [e.g. v0.65.0]

**Additional context**

**Comment by odenlerma** [comment]
try this
const CUSTOM_TOAST = React.forwardRef((props, ref) => (
    <Toast config={toastConfig} ref={ref} />
));

**Comment by calintamas** [comment]
There should be no need for a ref to the `<Toast />` instance. What is your use-case?

**Comment by oimolab** [comment]
After updating version from 1.6.0 to 2.1.3, same warning message also happened to me. But just removing  ref of <Toast /> solved this warning quickly as the above comment. Please try it.

**Comment by calintamas** [comment]
Indeed, the ref is no longer required in v2. See more here - [Quick start](https://github.com/calintamas/react-native-toast-message/blob/main/docs/quick-start.md#usage)
