### ISSUE TITLE
onHide is not called. v2.1.0

### ISSUE THREAD

**Issue by jackwullems** [calintamas/react-native-toast-message#332]
version 2.1.0
platform: iOS
deafualt config
Expected behavior:
onHide routine should be called when close action occurs or  disappears after visibilityTime.

**Comment by calintamas** [comment]
Hi @jackwullems, please add a repro. All tests checking for onHide being called are passing.

**Comment by jackwullems** [comment]
Sorry, it was my fault.
In my case toast is showing twice then the first toast's onHide is not calling.
