### ISSUE TITLE
Costumize Toast messages

### ISSUE THREAD

**Issue by angecas** [calintamas/react-native-toast-message#333]
Hello, can someone tell me if this package allows to costumize the toast messages in functional components? I am not being successfull even using useRef hooks. I would like to know, if someone manage doing it , can please explain me how ?

This package looked good because it shows on modals, but the default appearence doesnt go with rest of my app at all.

please, help?

**Comment by calintamas** [comment]
Hi @angecas, yes, you can create custom layouts (either by overloading existing toast types, or creating completely new ones). Here is the documentation: https://github.com/calintamas/react-native-toast-message/blob/main/docs/custom-layouts.md

Let me know if you have any questions
