### ISSUE TITLE
Show Toast above Modals

### ISSUE THREAD

**Issue by BrendanVadacoraBell** [calintamas/react-native-toast-message#34]
Great library. A feature I require, and I think many will too, is that the Toast can show above RN modals.

The use case is to have a single instance of the `Toast` component in the app, that is then shown via the `Toast.show` command. If I open a modal and while that modal is still open I show a toast, it currently opens behind the modal mask. Playing around with `zIndex` and similar hacks doesn't change much as RN Modal is a native component and opens above the rest of the app.

![IMG_E15E1E4FB8D3-1](https://user-images.githubusercontent.com/16708732/87021486-94fc9f00-c1d5-11ea-8640-b6e06c8f6e73.jpeg)

Adding the `Toast` to the content of the modal allowed the toast to be in the forefront, i.e. it is not hidden behind the modal, however, it cannot go outside of the bounds of the modal content. Playing around with negative margin or absolute/relative positioning did not help as the toast then doesn't display at all when in the mask area of the modal.

![IMG_044454ABABEE-1](https://user-images.githubusercontent.com/16708732/87022010-3257d300-c1d6-11ea-83b4-52ecec7a2f23.jpeg)

You can find a minimal demo [here](https://snack.expo.io/@brendanvadacorabell/toast-behind-modal)

**Comment by calintamas** [comment]
Hi @BrendanVadacoraBell. Unfortunately, this is not possible due to the way `Modal` is implemented in RN (a view that's above everything else).

**Comment by BrendanVadacoraBell** [comment]
Hi @calintamas, [here is an example of a library that does what I expect](https://www.npmjs.com/package/react-native-simple-toast), just the customization and API isn't as good as this. Perhaps it will give some insight on how to achieve this functionality.

**Comment by McSam94** [comment]
@BrendanVadacoraBell did you found a workaround solution?

**Comment by calintamas** [comment]
@McSam94 https://github.com/calintamas/react-native-toast-message#how-to-show-the-toast-inside-a-modal

**Comment by McSam94** [comment]
@calintamas . Thank you for replying. I manage to show the toast box in a modal. However, in ios when the modal slides down to dismiss, the toast container is sticking at the top and following the modal to slide down. Is there any workaround? 

<img width="468" alt="Screenshot 2021-06-08 at 1 42 52 PM" src="https://user-images.githubusercontent.com/39615910/121129749-fd2d8800-c85f-11eb-9081-0b75ba5cf656.png">

**Comment by muhammadtaha1998** [comment]
> @McSam94 https://github.com/calintamas/react-native-toast-message#how-to-show-the-toast-inside-a-modal

Hi. I trying this solution provided by you in the documentation but it doesn't seem to work. The doesn't show at all. Not even behind the modal.
`export default function FullScreenModal({
  title,
  isOpen,
  onClose,
  nextButton,
  keyboardShouldPersistTaps,
  children,
  leftIcon,
  handleLeftIcon,
}) {
  const modalToastRef = useRef();
  return (
    <View style={styles.centeredView}>
    <Modal
      animationType="slide"
      transparent={true}
      visible={isOpen}
      onRequestClose={onClose}>
      <Toast ref={modalToastRef} />
      <View style={styles.centeredView}>
        <View style={styles.modalView}>
          <ScrollView
            showsVerticalScrollIndicator={false}
            contentContainerStyle={styles.children}
            keyboardShouldPersistTaps={keyboardShouldPersistTaps || 'never'}>
            <SafeAreaView style={styles.safeAreaViewContainer}>
              <Header
                options={{
                  title: title,
                  rightIcon: (
                    <X
                      stroke={colors.white}
                      fill={colors.primary}
                      width={30}
                      height={30}
                    />
                  ),
                  handleRightIcon: onClose,
                  leftIcon,
                  handleLeftIcon,
                }}
              />
              <View>{children}</View>
            </SafeAreaView>
          </ScrollView>
        </View>
      </View>
      <Button
        value="Toast"
        onPress={() => {
          Toast.show({
            text1: 'Hello',
            text2: 'This is some something 👋',
          });
        }}
        style={styles.btnContainer}
      />
      <LinearGradient
        gradientOptions={{
          gradient: {start: 'rgba(0,0,0,1)', end: 'rgba(0,0,0,0)'},
          direction: {start: {x: 1, y: 1}, end: {x: 1, y: 0}},
        }}
        style={styles.shadow}
      />
    </Modal>
    </View>
  );
}`

Please reply ASAP

**Comment by tones31** [comment]
Yes, there is a simple solution. Any full screen modal should instead simply be a screen. There's not really any reason that a modal should be the entire size of your screen. That is a screen. Modals should only be used for "mini" screens. In fact a modal and a toast are not much different. Anyway, if you take this philosophy (took me about 10 mins of refactoring my modals to screens) you can avoid this issue that I don't think will ever be "fixed".

**Comment by maximewim** [comment]
> > @McSam94 https://github.com/calintamas/react-native-toast-message#how-to-show-the-toast-inside-a-modal
> 
> Hi. I trying this solution provided by you in the documentation but it doesn't seem to work. The toast doesn't show at all. Not even behind the modal.
> 
> ```
> export default function FullScreenModal({
>   title,
>   isOpen,
>   onClose,
>   nextButton,
>   keyboardShouldPersistTaps,
>   children,
>   leftIcon,
>   handleLeftIcon,
> }) {
>   const modalToastRef = useRef();
>   return (
>     <View style={styles.centeredView}>
>     <Modal
>       animationType="slide"
>       transparent={true}
>       visible={isOpen}
>       onRequestClose={onClose}>
>       <Toast ref={modalToastRef} />
>       <View style={styles.centeredView}>
>         <View style={styles.modalView}>
>           <ScrollView
>             showsVerticalScrollIndicator={false}
>             contentContainerStyle={styles.children}
>             keyboardShouldPersistTaps={keyboardShouldPersistTaps || 'never'}>
>             <SafeAreaView style={styles.safeAreaViewContainer}>
>               <Header
>                 options={{
>                   title: title,
>                   rightIcon: (
>                     <X
>                       stroke={colors.white}
>                       fill={colors.primary}
>                       width={30}
>                       height={30}
>                     />
>                   ),
>                   handleRightIcon: onClose,
>                   leftIcon,
>                   handleLeftIcon,
>                 }}
>               />
>               <View>{children}</View>
>             </SafeAreaView>
>           </ScrollView>
>         </View>
>       </View>
>       <Button
>         value="Toast"
>         onPress={() => {
>           modalToastRef.current.show({
>             text1: 'Hello',
>             text2: 'This is some something 👋',
>           });
>         }}
>         style={styles.btnContainer}
>       />
>       <LinearGradient
>         gradientOptions={{
>           gradient: {start: 'rgba(0,0,0,1)', end: 'rgba(0,0,0,0)'},
>           direction: {start: {x: 1, y: 1}, end: {x: 1, y: 0}},
>         }}
>         style={styles.shadow}
>       />
>     </Modal>
>     </View>
>   );
> }
> ```
> 
> Please reply ASAP

For me, it only work if I place the Toast component after the content of my modal. 

For instance, this will work : 
```
<Modal>
  <MyContent>
  </MyContent>
  <Toast/>
</Modal> 
```
and this not : 
```
<Modal>
  <Toast/>
  <MyContent>
  </MyContent>
</Modal> 
```

**Comment by hromovp** [comment]
Here is my take on the issue.
I've had to create new Toast reference, because I already had one project-wise and default reference assignment from documentation was braking reference to default project-wise toast, and they didn't work after opening this one.
  
Basically I am storing toast right under the top of the modal content, and it slides fast from the top. as it is on regular screens, omitting wasting time for animation if modal is more then half screen size. 
Also content might change dynamically and toast will always show up as intended.

Hope this helps

```
const [modalListHeight, setModalListHeight] = useState(0); // tracking modal container size
const modalToast = useRef({} as Toast); // create here new Toast
 ... 
<Modal>
    <View onLayout={(height) => setModalListHeight(height.nativeEvent.layout.height)}>
  ...
    <Toast
      config={config} // here just reusing project's default config, you might not need it
      ref={(ref) => (modalToast.current = ref)}
      style={{
        bottom: modalListHeight,
        zIndex: -1,
       }}
      position={'bottom'}
      bottomOffset={15} // customizing offset from the top of the modal when toast is showing
    />
</Modal>
```

**Comment by mMarcos208** [comment]
zIndex: -1 in styles work for me

**Comment by mMarcos208** [comment]
https://github.com/calintamas/react-native-toast-message/blob/main/docs/modal-usage.md

**Comment by bekatru** [comment]
How about "containedTransparentModal"?

**Comment by AleeFarook** [comment]
@calintamas , react native toast message is not showing above the Modals In ios, 

`  return (
    <SafeAreaProvider>
      <NavigationContainer ref={navigationRef}>
        <RootStack.Navigator headerMode='none' screenOptions={{ headerShown: false, gestureEnabled: false }}>
          <RootStack.Screen name='StackNavigation' component={StackNavigation} />
        </RootStack.Navigator>

        {openedModals.length == 0 &&
          <Toast config={toastConfig} />
        }
        
            <SafeAreaProvider>
      <NavigationContainer ref={navigationRef}>
      )`
      This is my app.js code, I have redux state array which store the name of modal so this Toast instance refer only when there is no modal open and in Each modal I have Toast instance but it is not working, So it only work in android , But IOS it is not working yet ?
      
      help me 🙏

**Comment by AleeFarook** [comment]
I have the latest version of the package

**Comment by LinxZW** [comment]
This can be easily solve if you add <Toast/> inside the <Modal>, however you need to add    {visible && (<Toast config={toastConfig} />)}, where visible is the visibility of the modal, so in this case it won't affect other toast message.

**Comment by asliddintursunov** [comment]
Hi, Same issue here. I solved it by reading [How to show the Toast inside a Modal](https://github.com/calintamas/react-native-toast-message/blob/main/docs/modal-usage.md).

We just need to put `<Toast />` at the bottom of the `<Modal>` too.

So it will look like something like this...



`<Modal>
        <Toast />
⁣</Modal>`

**Comment by youcefswoo** [comment]
I tried adding the Toast instance inside the modal, but I encountered the same issue mentioned in [this comment](https://github.com/calintamas/react-native-toast-message/issues/34#issuecomment-1600546725). Basically, the toast message was appearing from the top of the modal instead of the top of the screen. The workaround that worked for me is to keep the Toast instance only in the root file (`App.tsx`) and wrap it with <Portal> from [@gorhom/portal](https://github.com/gorhom/react-native-portal). Here is a snippet of the code from `App.tsx`:

 ```
<>
   ...
   <Portal>
      <FullWindowOverlay style={StyleSheet.absoluteFill}>
        <Toast />
      </FullWindowOverlay>
   </Portal>
<>
```

**Comment by FilipSavic95** [comment]
All I had to do:
```
      <PersistQueryClientProvider client={queryClient} persistOptions={{ persister: queryClientPersister }}>
        <GestureHandlerRootView style={{ flex: 1 }}>
          <TelemetryProvider>
            <GluestackUIProvider>
              <MYOErrorBoundary>
                <Navigation />
              </MYOErrorBoundary>
            </GluestackUIProvider> // Toast was on this line
            <Toast config={toastConfig} /> // so I just moved it outside of GluestackUIProvider
          </TelemetryProvider>
        </GestureHandlerRootView>
      </PersistQueryClientProvider>
```

![Image](https://github.com/user-attachments/assets/2d5211c3-a506-49c3-ad2d-a33f4b6d729c)
