### ISSUE TITLE
Toast Message does not hide completely if dynamic height is greater then 60 

### ISSUE THREAD

**Issue by sdumjahn** [calintamas/react-native-toast-message#35]
Each time you call `Toast.show()` the value of `height` in the internal state is set to 60 ([src/index.js line 164](https://github.com/calintamas/react-native-toast-message/blob/master/src/index.js#L164) with line [38](https://github.com/calintamas/react-native-toast-message/blob/master/src/index.js#L38)).

There is the function `onLayout` which sets the value of `state.height` to the real height of the component, but this function is only called when the real height of the component changed! So if we call `Toast.show()` with a real height of 80, the value of `state.height` is set from it initial value of 60 to 80. 
But if we call `Toast.show()` again, with the same text and so with the same real height of 80, the value of `state.height` is set back to 60 and remains 60, because `onLayout` is not called since the real height of the notification remains the same.
The result of the wrong height is, that the animation does not hide the message completely.

My solution: 
Add the following line `height: this.state.height,` directly after [src/index.js line 164](https://github.com/calintamas/react-native-toast-message/blob/master/src/index.js#L164) to restore the old height from the last call. 
If the real height differ from the first and the second call to `Toast.show()` then `onLayout` get called and the height will be adjusted.

**Comment by sdumjahn** [comment]
The same problem occurs on other layout related fields as well (e.g. topOffset, bottomOffset). 
So I question, why the reset of the layout is necessary? In my case it only produces problems.

**Comment by calintamas** [comment]
@sdumjahn Hi, sorry for the late response, been caught up for a while now. I'll take a look

**Comment by calintamas** [comment]
@sdumjahn published your solution in [v1.3.2](https://github.com/calintamas/react-native-toast-message/tree/v1.3.2)
