### ISSUE TITLE
Swiping up in ios , creates an empty toast in bottom position.

### ISSUE THREAD

**Issue by Mansi-Bigstep** [calintamas/react-native-toast-message#354]
**Describe the bug**

**Steps to reproduce**
2. Tap on '....'

**Expected behavior**

**Screenshots**

**Code sample**
To help debugging, please add a code sample that reproduces the issue.

**Environment (please complete the following information):**
 - OS: [iOS, Android, Web]
 - react-native-toast-message version: [e.g. v2.0.0]
 - react-native version [e.g. v0.65.0]

**Additional context**

**Comment by Saalim95** [comment]
I am also having the similar issue in android. When I swipe slightly down at the top of screen an empty Toasts shows up.

**Comment by Mansi-Bigstep** [comment]
try props.isVisible and render differnt component accordingly.

**Comment by Mansi-Bigstep** [comment]
try props.isVisible and render differnt component accordingly.

**Comment by purrsZ** [comment]
you can pass in "config" props field success :()=>{}
