### ISSUE TITLE
Error: Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by itea2828** [calintamas/react-native-toast-message#398]
In latest version of expo I am getting the following error

**Comment by tankers746** [comment]
Seems to be an issue when title is an empty string

**Comment by HaithamOumerzoug** [comment]
You have to specify the toast title.
`
 const showToast = (type, title, body) => {
    Toast.show({
      type: type,
      text1: title,
      text2: body,
     // other options
    });
  };
`

**Comment by tyartyartyar** [comment]
@itea2828 happened to me as well after updating to version ^2.0.0 resolved 2.1.5
it throws this error when either text1 or text2 is empty string, try to give some whitespace (e.g " ") for temporary workaround 🍻
