### ISSUE TITLE
Damping value must be grater than 0

### ISSUE THREAD

**Issue by HeroSony** [calintamas/react-native-toast-message#41]
Sometime when I moved from screen while toast message not yet hided and back to another screen and draged it to hide, it show error message 'Damping value must be greater than 0'.

**Comment by HeroSony** [comment]
I've checked on src/index.js file
```
_animateRelease(gesture) {
    const { position, animation } = this.state;
    const { dy, vy } = gesture;
    let value = 1 + dy / 100;

    if (position === 'bottom') {
      value = 1 - dy / 100;
    }

    if (value < 0.65) {
      Animated.spring(animation, {
        toValue: -2,
        //speed: -vy,      <----  
        speed: vy,
        useNativeDriver: true
      }).start(() => {
        const { onHide } = this.state;
        if (onHide) {
          onHide();
        }
      });
    } else if (value < 0.95) {
      Animated.spring(animation, {
        toValue: 1,
        velocity: vy,
        useNativeDriver: true
      }).start();
    }
  }
```
After changed speed option to position value it's not getting error anymore.

**Comment by BogdanHossu** [comment]
This is an issue that I am currently having, seems like it occurs only if you set the position to bottom so the vy should be reversed. @calintamas we could basically just have `speed: position === 'bottom' ? vy : -vy` or maybe i'm missing something?
