### ISSUE TITLE
Shadows not visible on Android

### ISSUE THREAD

**Issue by akshitrcrm** [calintamas/react-native-toast-message#43]
in v1.3.2
Missed `elevation` property in styles. They show in iOS.
In src/components/base/styles.js
In base object, if I provide elevation, it works.

**Comment by calintamas** [comment]
elevation was removed due to #6

**Comment by calintamas** [comment]
@akshitrcrm Indeed, it was weird, but it's some Android layout bug I suppose (related to elevation + absolute positioning).
As for a workaround, I'm not sure, maybe a dark gray border?

**Comment by DerekFei** [comment]
@calintamas I think provide a style prop allowing us to change background color and border would be good enough

**Comment by DerekFei** [comment]
I just created a PR to fix this issue: https://github.com/calintamas/react-native-toast-message/pull/51

**Comment by calintamas** [comment]
@DerekFei @akshitrcrm merged, released in `v1.3.4`
