### ISSUE TITLE
8px bottom offset

### ISSUE THREAD

**Issue by apapalillo** [calintamas/react-native-toast-message#430]
Hi, I have updated react-native-toast-message from 1.4.9 to the latest version (2.1.5). I've noticed it has a bottom offset of approximately 8px now.

I've checked the config and it has bottomOffset set to 0 but I'm still having that extra margin after updating.

The root view of my custom Toast only has a 100% width attribute to its style, nothing else.

I can't find why is that. It's an intended behavior?

**Comment by kesteer** [comment]
@apapalillo  

You can fix this issue by making a custom toast component and using a style of `bottom: -8px`.

**Comment by faqini** [comment]
Hi, thanks for this great lib, same issue after upgrading,  I'm getting 8px on Android and 10px on iOS with a custom toast.
The negative `bottom` props works but as mentioned `bottomOffset: 0` doesn't do much.

![Screenshot 2023-03-07 at 16 42 31](https://user-images.githubusercontent.com/5808430/223472665-b3563fd9-8b64-42e1-b812-075e91d74362.png)

**Comment by seyedmostafahasani** [comment]
@apapalillo you can set `keyboardOffset : 0` then you will see how it will remove the gap.

**Comment by apapalillo** [comment]
> @apapalillo you can set `keyboardOffset : 0` then you will see how it will remove the gap.

This really fixed my issue without having to set a negative margin! thanks!
