### ISSUE TITLE
Export a base toast that can accept any content

### ISSUE THREAD

**Issue by dominictwlee** [calintamas/react-native-toast-message#471]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the base toast functionality (with the touchable dismiss), while being able to fully customize the contents of a toast. Could be some other component with base functionality without any styling opinions.

**Describe the solution you'd like**
```
<BaseHeadlessToast> // retains touchable functionality
  <CustomText />
  <CustomContent />
</BaseHeadlessToast>
```

**Describe alternatives you've considered**
Could implement it from scratch, but I reckon it'd be nice to make the base toast more composable.

**Additional context**

**Comment by calintamas** [comment]
Already possible, see `tomatoToast` in the example: https://github.com/calintamas/react-native-toast-message/blob/main/docs/custom-layouts.md#create-custom-layouts
