### ISSUE TITLE
Toast not showing on RN v0.72.4

### ISSUE THREAD

**Issue by jmada** [calintamas/react-native-toast-message#486]
**Describe the bug**
The library isn't working on RN v0.72.4, it doesn't show the "toast" dialog.

**Steps to reproduce**
Just following the the quick start -> https://github.com/calintamas/react-native-toast-message/blob/main/docs/quick-start.md

**Expected behavior**
It should show the toast dialog like the example.

**Screenshots**
Nothing to add.

**Code sample**
```
// Foo.jsx
import Toast from 'react-native-toast-message';
import { Button } from 'react-native'

export function Foo(props) {
  const showToast = () => {
    Toast.show({
      type: 'success',
      text1: 'Hello',
      text2: 'This is some something 👋'
    });
  }

  return (
    <Button
      title='Show toast'
      onPress={showToast}
    />
  )
}
```

**Environment (please complete the following information):**
 - OS: Android
 - react-native-toast-message version: 2.1.6
 - react-native version: 0.72.4

**Additional context**
Nothing to add.

**Comment by Alan-Graton** [comment]
Same over here:

## App.tsx
```javascript
import { StatusBar } from "expo-status-bar";
import { SafeAreaProvider } from "react-native-safe-area-context";
import { RootSiblingParent } from "react-native-root-siblings";
// Screens
import { Home } from "./src/screens/Home/Home";
// Styles
import Toast from "react-native-toast-message";

export default function App() {
  return (
    <>
      <SafeAreaProvider>
        <RootSiblingParent>
          <Toast />
          <Home />
          <StatusBar style="inverted" />
        </RootSiblingParent>
      </SafeAreaProvider>
    </>
  );
}
```

## Home(calling Toast)
```javascript
import { Toast } from "react-native-toast-message/lib/src/Toast";

export function Home() {
function handleCreate(task: string): void {
    if (tasks.find((el) => el.description === task)) {
      // FIXME: Toast not displaying
      Toast.show({
        type: "error",
        text1: "Opa!",
        text2: "Você já cadastrou uma tarefa igual a essa",
      });
      return;
    }

    setTasks((prev) => [...prev, { description: task, status: "unchecked" }]);
  }
  {...}
}
```

## Environment
- Windows 10
- react-native version: 0.72.5
- react-native-toast-message: ^2.1.6

**Comment by KaviduAloka** [comment]
@jmada @Alan-Graton try adding `<Toast />` in the bottom of `StackNavigation`

```
export default function App() {
  return (
    <>
      <SafeAreaProvider>
        <RootSiblingParent>
          <Home />
          <StatusBar style="inverted" />
          <Toast />  //  in the bottom of other components
        </RootSiblingParent>
      </SafeAreaProvider>
    </>
  );
}
```

**Comment by Alan-Graton** [comment]
> @jmada @Alan-Graton try adding `<Toast />` in the bottom of `StackNavigation`
> 
> ```
> export default function App() {
>   return (
>     <>
>       <SafeAreaProvider>
>         <RootSiblingParent>
>           <Home />
>           <StatusBar style="inverted" />
>           <Toast />  //  in the bottom of other components
>         </RootSiblingParent>
>       </SafeAreaProvider>
>     </>
>   );
> }
> ```

@KaviduAloka Thanks for the tip, will give a try

**Comment by gemasaputera** [comment]
I faced the same problem, any updates for this issue ?

`
  return (
    <ContextProvider>
      <Navigation />
      <Button title="Sign out" onPress={signOut} />
      <Toast />
    </ContextProvider>
  );`
  
  I've added  <Toast /> in the bottom of my App.tsx

**Comment by jeetvani** [comment]
> @jmada @Alan-Graton try adding `<Toast />` in the bottom of `StackNavigation`
> 
> ```
> export default function App() {
>   return (
>     <>
>       <SafeAreaProvider>
>         <RootSiblingParent>
>           <Home />
>           <StatusBar style="inverted" />
>           <Toast />  //  in the bottom of other components
>         </RootSiblingParent>
>       </SafeAreaProvider>
>     </>
>   );
> }
> ```

Works For Me

**Comment by jmada** [comment]
> @jmada @Alan-Graton try adding `<Toast />` in the bottom of `StackNavigation`
> 
> ```
> export default function App() {
>   return (
>     <>
>       <SafeAreaProvider>
>         <RootSiblingParent>
>           <Home />
>           <StatusBar style="inverted" />
>           <Toast />  //  in the bottom of other components
>         </RootSiblingParent>
>       </SafeAreaProvider>
>     </>
>   );
> }
> ```

Worked for me! Thank you so much. I'm closing the issue. :)

**Comment by ritikRidingad** [comment]
this my home.ts file where i am using navigation container 

```typescript 
return (
    <>
      <NavigationContainer>
         <Toast/>
        <Stack.Navigator
          initialRouteName={!accessToken ? "homeStack" : "login"}
        >
          <Stack.Screen
            name="onBoarding"
            component={OnBoard}
            options={{ headerShown: false }}
          />
          <Stack.Screen
            name="signup"
            component={SignUp}
            options={{ headerShown: false }}
          />
          <Stack.Screen
            name="login"
            component={Login}
            options={{ headerShown: false }}
          />
          <Stack.Screen
            name="forgetPassword"
            component={ForgetPassword}
            options={{ headerShown: false }}
          />
          <Stack.Screen
            name="resetPassword"
            component={ResetPassword}
            options={{ headerShown: false }}
          />
          <Stack.Screen
            name="otp"
            component={Otp}
            options={{ headerShown: false }}
          />
          <Stack.Screen
            name="homeStack"
            component={TabNavigation}
            options={{ headerShown: false }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </>
  );
}

```

and this is my App.tsx file 


```typescript
export default function App(): React.JSX.Element {
  return (
    <Provider store={store}>
      <Main />
    </Provider>
  );
}
```


toast is not showing i want the tost should be occured in top right corner 

please help

react native version  iam using  v0.73.7
