### ISSUE TITLE
How can I change style of Toast?

### ISSUE THREAD

**Issue by oscarcornejo** [calintamas/react-native-toast-message#50]

**Comment by calintamas** [comment]
@oscarcornejo https://github.com/calintamas/react-native-toast-message#customizing-the-toast-types

**Comment by Dallas62** [comment]
Hi @calintamas 
I'm running into the same issue.
If I want to change some values of the style (text-size), I don't have other choices than recreate the whole component which provide a bad developer-experience.
The initial design is great but allow some adjustment would be cool !

**Comment by calintamas** [comment]
@Dallas62 Hi, thanks for the feedback! 
I'll think of a way to support that, while keeping the current method of customizing types. Maybe exporting each default component and allowing style props for them.

**Comment by thanveershah** [comment]
> @Dallas62 Hi, thanks for the feedback! I'll think of a way to support that, while keeping the current method of customizing types. Maybe exporting each default component and allowing style props for them.

Is changing the background possible now?

**Comment by rie-kumar** [comment]
I would like to know if this is possible now too! Also, love this package.

**Comment by melnikovkolya** [comment]
Hi folks,

You can do it as follows:

```
<Toast
  config={{
    success: (props) => (
      <SuccessToast
        {...props}
        contentContainerStyle={toastContentContainerStyle}
        text1Style={toastText1Style}
      />
    ),
    error: (props) => (
      <ErrorToast
        {...props}
        contentContainerStyle={toastContentContainerStyle}
        text1Style={toastText1Style}
      />
    ),
    info: (props) => (
      <InfoToast
        {...props}
        contentContainerStyle={toastContentContainerStyle}
        text1Style={toastText1Style}
      />
    ),
  }}
/>
```
