### ISSUE TITLE
How to override the default duration for the Toast at root level for all instances?

### ISSUE THREAD

**Issue by badalsaibo** [calintamas/react-native-toast-message#517]
Same as question. I don't want to go to each Toast.show and add a custom duration. Instead maybe set it somewhere in the toastConfig itself? Didn't find the documentation for this in the API

**Comment by calintamas** [comment]
`visibilityTime` can be passed [as prop](https://github.com/calintamas/react-native-toast-message/blob/main/docs/api.md#props) to the root Toast instance.

```js
<Toast visibilityTime={4000} />
```
