### ISSUE TITLE
Android status bar has bottom shadow

### ISSUE THREAD

**Issue by calintamas** [calintamas/react-native-toast-message#6]
When status bar is white, there's a bottom shadow.

To fix this, set `elevation: 0` when toast message is hidden.

**Comment by mav10** [comment]
@calintamas as I understood it was not merged yet? Are you going to fix it

**Comment by calintamas** [comment]
@mav10 Hope I'll have the time to fix it this weekend.

**Comment by mav10** [comment]
ok, thanks :)

**Comment by calintamas** [comment]
fixed by #10

**Comment by calintamas** [comment]
@mav10 available in release 1.2.3
