### ISSUE TITLE
Cannot read property show of undefined

### ISSUE THREAD

**Issue by mariobrubio** [calintamas/react-native-toast-message#62]
Hi,

I'm trying to show the toast but the show function keeps telling me that the Toast is undefined, I'm including the toast inside my App.js and then calling it with 
`Toast.show({
      text1: "hello",
    });`

**Comment by calintamas** [comment]
Hi @mariobrubio 
Are you setting the ref in Root?

Docs here https://github.com/calintamas/react-native-toast-message#usage

**Comment by vick16ach** [comment]
@calintamas  Where to place the root.jsx file is important information it seems.

**Comment by calintamas** [comment]
@vick16ach by root I mean the entry point in your app

**Comment by vick16ach** [comment]
Entry point is App.js and i'm using StackNavigator there. How can i paste this code in that file ? It is already returning App !

**Comment by calintamas** [comment]
you can do it like this
```
<>
   <RootNavigator />   
   <Toast />
</>
```

**Comment by vick16ach** [comment]
My code looks like this
```
export default function App() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
        {/* Home Screen for testing navigation */}
        {/* <Stack.Screen name="Home Page" component={HomeScreen} options={{ title: 'Overview' }} /> */}
        <Stack.Screen
          name="Login Page"
          component={login}
          options={{headerShown: false}}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

**Comment by calintamas** [comment]
you can render it outside the nav container
```js
return (
    <>
      <NavigationContainer>...</NavigationContainer>
      <Toast ref={(ref) => Toast.setRef(ref)} />
    </>
  );
```

**Comment by vick16ach** [comment]
Hey, can you kindly tell me what is Toast in <Toast ref={(ref) => Toast.setRef(ref)} /> . Where do i import it from ?

**Comment by calintamas** [comment]
```js
import Toast from 'react-native-toast-message';
```

**Comment by vick16ach** [comment]
This is really very confusing thing. Whats the purpose of root.jsx then, Where it is being used. What this whole concept is about in javascript. A proper documentation is necessary it seems.

**Comment by calintamas** [comment]
@vick16ach `Root` is the entry point in your app (I called it "root" for convenience, it can be called anything). To be able to "call" the `Toast` in any screen, you have to render it in the entry point (the "root") and set a reference to it. So, you entry point becomes:

```js
// entry point (root)
import React from 'react';
// ...
import Toast from 'react-native-toast-message';

export default function App() {
  return (
    <>
      <NavigationContainer>
        <Stack.Navigator>
          {/* Home Screen for testing navigation */}
          {/* <Stack.Screen name="Home Page" component={HomeScreen} options={{ title: 'Overview' }} /> */}
          <Stack.Screen
            name='Login Page'
            component={login}
            options={{ headerShown: false }}
          />
        </Stack.Navigator>
      </NavigationContainer>
      <Toast ref={(ref) => Toast.setRef(ref)} />
    </>
  );
}

```

Then on any screen you want to "call" the `Toast`, you only need to import the library and call `Toast.show`

```js
// some screen
import React from 'react'
import { TouchableOpacity, Text } from 'react-native'
import Toast from 'react-native-toast-message'

function MyComponent(props) {
  const showToast = () => Toast.show({
    type: 'success',
    text1: 'Hello'
  })
  return (
    <TouchableOpacity onPress={showToast}>
        <Text>Show toast</Text>
      </TouchableOpacity>    
  )
}

export default MyComponent
```

**Comment by vick16ach** [comment]
Oh This is so simple, I'm very new to react native and confused a lot. I think it would be better to change root.jsx as app.js and mention it as entry point file.  So, There would be no confusions for beginners. Thank you

**Comment by calintamas** [comment]
Sure, no worries 👍

**Comment by kamal-hossain** [comment]
This was a very helpful Issue. 
Thanks for the above discussions. 
# @vikasacharya16 and @calintamas
