### ISSUE TITLE
Hi,  I'm trying to show the toast but the show error ref.show cant be undefidend,

### ISSUE THREAD

**Issue by AmmarKhan21** [calintamas/react-native-toast-message#63]
can you kindly help me how i can add ref in root in expo . i create this Root component and also try expo api to register it root named registerRootComponent bur same error kindly can you help me?

**Comment by calintamas** [comment]
Hi @AmmarKhan21 
Can you put the code here?

An example of the way it should be added is here - https://github.com/calintamas/react-native-toast-message#usage

**Comment by vick16ach** [comment]
@calintamas what is root ? where to put that file ?

**Comment by AmmarKhan21** [comment]
i manged to git rid error but i not able to use it because when i used it in component it shows below ny my content and remain sticky so i left this package and use similar version of toast which is provided by expo
