### ISSUE TITLE
Unable to close Toast using the cross icon

### ISSUE THREAD

**Issue by sahilvicesoftware** [calintamas/react-native-toast-message#64]
Unable to close Toast using the cross icon

**Comment by sahilvicesoftware** [comment]
It worked.Was a z-index issue

**Comment by xhirazi** [comment]
+1

on XS Max

**Comment by anilios** [comment]
I am also having this issue. Where do i have to set zIndex?

**Comment by kamal-hossain** [comment]
@anilios check [this](https://github.com/calintamas/react-native-toast-message/issues/167#issuecomment-819219863) out. Maybe this will help you.
