### ISSUE TITLE
Implement with KeyboardAvoidingView?

### ISSUE THREAD

**Issue by JosieN92** [calintamas/react-native-toast-message#65]
I wanted to try and use this where the error would show above the on-screen keyboard if a user was entering text? But then appear at the bottom again if the keyboard is dismissed.

I've tried adding Toast.show etc. within a KeyboardAvoidingView but that doesn't seem to work. 

Any thoughts?

**Comment by calintamas** [comment]
@JosieN92 Indeed, that use case is not covered. So it's not possible at the moment.
I'll mark it as an enhancement, thanks 👍
