### ISSUE TITLE
Doesn't show at all

### ISSUE THREAD

**Issue by VanTigranyan** [calintamas/react-native-toast-message#67]
Hey @calintamas . I have a problem with this package. After installing I have tried to call the show function in different modules in my react-native app. But the toast doesn't show up at all, nowhere. I guess that is because of react-navigation and the usage of stack-navigator, and the message shows up under the screens. Is this problem a common one? And is there a solution? I can find nothing, but I really like this package and would like to use it. Thanks in advance.

**Comment by artak1995** [comment]
> Hey @calintamas . I have a problem with this package. After installing I have tried to call the show function in different modules in my react-native app. But the toast doesn't show up at all, nowhere. I guess that is because of react-navigation and the usage of stack-navigator, and the message shows up under the screens. Is this problem a common one? And is there a solution? I can find nothing, but I really like this package and would like to use it. Thanks in advance.

same

**Comment by calintamas** [comment]
As long as the `Toast` is rendered in the entry point alongside navigation, it should show up.

Can you paste here the code from the entry point of your app?

**Comment by MesterLum** [comment]
I'm getting almost the same problem with it. I can't show up the Toast.

**Comment by brvhprince** [comment]
> Hey @calintamas . I have a problem with this package. After installing I have tried to call the show function in different modules in my react-native app. But the toast doesn't show up at all, nowhere. I guess that is because of react-navigation and the usage of stack-navigator, and the message shows up under the screens. Is this problem a common one? And is there a solution? I can find nothing, but I really like this package and would like to use it. Thanks in advance.

Add the toast reference at the of the Navigation Container 

`<NavigationContainer>

//navigation screens and other stuffs

 <Toast ref={(ref) => Toast.setRef(ref)} />
</NavigationContainer>
`

If you have a provider inside the NavigatioContainer, add it as the last child in the Provider.

**Comment by xmflsct** [comment]
@brvhprince method works. So I have:
```
<NavigationContainer>
  <Tab.Navigator>
    <Tab.Screen />
  </Tab.Navigator>

  <Toast ref={(ref: any) => Toast.setRef(ref)} />
</NavigationContainer>
```

**Comment by xavhoff** [comment]
This should be written somewhere in the documentation, thanks @brvhprince

**Comment by hungdev** [comment]
@calintamas I think you should write it in the document.

**Comment by Billmike** [comment]
@calintamas Petition to write this in the documentation 😅 . This should be written in the docs so as to avoid hair-pulling 😅

**Comment by calintamas** [comment]
Indeed, I should have done this earlier. Now it's there - https://github.com/calintamas/react-native-toast-message#how-to-render-the-toast-when-using-react-navigation.

Thanks everyone!

**Comment by mrroll** [comment]
We also probably want to point out that it has to be the very last child of the `NavigationContainer` component.
