### ISSUE TITLE
Setting position: 'bottom' animates from top the first time the toast appears

### ISSUE THREAD

**Issue by pdugan20** [calintamas/react-native-toast-message#70]
![1](https://user-images.githubusercontent.com/1837100/97573285-e23c9080-19bf-11eb-86e2-7d8caa5d760a.gif)

I'm rendering this in my appNavigation with:
```
<Toast
    config={toastConfig}
    ref={(ref) => Toast.setRef(ref)}
    bottomOffset={80}
/>
```

and then calling with:
`Toast.show({`` text1, position: 'bottom', type: 'success' });`

Any ideas?

**Comment by pdugan20** [comment]
I can solve for this by firing an invisible toast when the app first loads that sets the position to bottom, at which point all subsequent visible toasts animation from bottom. Is there a better way to do this?

**Comment by calintamas** [comment]
Hi @pdugan20, thanks for using the lib!

Can you paste `toastConfig` here? Is your custom `type: success` having some animation or absolute positioning? 
Also, what you can try is to render the default `success` type and see if you can reproduce the issue. In this way, we could maybe narrow it down

**Comment by pdugan20** [comment]
Yup, toastConfig looks like:
```
export const toastConfig = {
    success: (internalState) => {
        return <ToastComponent text={internalState.text1} />;
    },
    init: () => {
        return null;
    },
};
```

and the component itself is using absolute positioning. Assuming this is incompatible when the positioning is absolute?

**Comment by calintamas** [comment]
Yes, no need to use absolute positioning on `ToastComponent`. Try without and let me know

**Comment by pdugan20** [comment]
OK thats grat to know. Is there an easy way to make the toast full width then?

**Comment by calintamas** [comment]
Sure, go with a `width: 100%` on `ToastComponent`
