### ISSUE TITLE
I can't install library.

### ISSUE THREAD

**Issue by JDBONFOR** [calintamas/react-native-toast-message#71]
Hi guys, I can't install library on my Expo project because I show message on my code that say: **Could not find a declaration file for module 'react-native-toast-message'. .../node_modules/react-native-toast-message/index.js' implicitly has an 'any' type. Try `npm install @types/react-native-toast-message` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-toast-message';`**
Any suggestion? My app is JS not TS.

**Comment by nikosantis** [comment]
I have the same problem!

**Comment by calintamas** [comment]
I'll take a look, thanks for raising it!

**Comment by Jery972** [comment]
got the same message also :x

**Comment by catodapice** [comment]
same here

**Comment by calintamas** [comment]
Type declaration has been added in `v1.3.7`. Please re-check
