### ISSUE TITLE
null is not an object (evaluating 'this._ref.show')

### ISSUE THREAD

**Issue by ariesbrylle-bms** [calintamas/react-native-toast-message#82]
Here's my code in app.js

`const App = createAppContainer(switchNavigator);

export default () => {
  return (
    <AuthProvider>
      <Toast ref={(ref) => Toast.setRef(ref)} />
      <App
        ref={(navigator) => {
          setNavigator(navigator);
        }}
      />
    </AuthProvider>
  );
};`

Here's my code on my login.js that uses notification.

`const LoginScreen = ({ navigation }) => {
  // initialized Auth Context
  Toast.show({
    text1: "Hello",
    text2: "This is some something 👋",
  });`

....

**Comment by moussouba** [comment]
Hi guy, uninstall `npm uninstall react-native-toast-message` and reinstall with `yarn add react-native-toast-message` it work for me

**Comment by ariesbrylle-bms** [comment]
will try. Thank you.

**Comment by ariesbrylle-bms** [comment]
zsh: command not found: yarn

That's the error I received. Will there be a problem if I'm using npm then switch to yarn?

**Comment by moussouba** [comment]
install yarn through [this link](https://classic.yarnpkg.com/en/docs/install/#debian-stable)

**Comment by ariesbrylle-bms** [comment]
Hello, I was able to use yarn instead of npm. I will now close this issue. Thank you very much for your help.

**Comment by rogerkerse** [comment]
This issue still exists with more common npm install so its not a viable solution

**Comment by calintamas** [comment]
With @rogerkerse's contribution, published the fix in [v1.3.5](https://github.com/calintamas/react-native-toast-message/releases/tag/v1.3.5)

**Comment by AshotN** [comment]
I'm still getting this error but the toasts work. Any ideas?
`[Unhandled promise rejection: TypeError: null is not an object (evaluating 'Toast._ref.show')]`
