### ISSUE TITLE
Bring on top of modal

### ISSUE THREAD

**Issue by gsavvid** [calintamas/react-native-toast-message#85]
Hi, thanks for this nice library. 

In our app we use modals to show bottom sheets which cover about 80% of the screen. If we show the Toast while one of these modals is open, then the Toast is shown behind the modal. Is there a way to bring the Toast on top of every other modal?

Thanks in advance.

**Comment by calintamas** [comment]
@gsavvid Only by rendering the Toast inside the Modal, as far as I know

**Comment by t-mohsin** [comment]
@calintamas If I render the Toast inside the modal & have one in App.js it gives an error **TypeError: null is not an object (evaluating 'Toast._ref.show')**

We can only render Toast once? If yes, then how can we bring it on the top of the modal ensuring it works perfectly on the rest of the screens.

**Comment by t-mohsin** [comment]
> @gsavvid Only by rendering the Toast inside the Modal, as far as I know

@calintamas If I render the Toast inside the modal & have one in App.js it gives an error TypeError: null is not an object (evaluating 'Toast._ref.show')

We can only render Toast once? If yes, then how can we bring it on the top of the modal ensuring it works perfectly on the rest of the screens.

**Comment by calintamas** [comment]
@t-mohsin try this https://github.com/calintamas/react-native-toast-message/issues/164#issuecomment-803556361
