### ISSUE TITLE
Add an `onPress` to BaseToast

### ISSUE THREAD

**Issue by caleb-harrelson** [calintamas/react-native-toast-message#86]
As far as I can tell, there isn't a way to keep the default toast formatting and also add an `onPress` to the toast while still keeping the ability to dismiss it. 

My use case is for duplicating the behavior of notifications that deep link within the app when clicked. When the app is active I'm using toasts to show the notifications and want the user to be able to either navigate to that part of the app by clicking the toast, or dismiss it as normal and stay where they are.

**Comment by caleb-harrelson** [comment]
I [forked the repo](https://github.com/StratusCode/react-native-toast-hook) and made a couple small changes... 😳

- It's been rewritten entirely in typescript (#71) with a new API using react context and hooks.
- Added ability to [set global defaults](https://github.com/StratusCode/react-native-toast-hook#global-customizations) for toasts on the ToastProvider (#50, #68, #97, #98).
- All internals and types are exported for customization (#50, #68, #87, #97, maybe #85).
- Added a queue for toasts -- if you queue a toast while one is already shown it will appear after the current one is gone (related to #37, though not stackable).
- Switched out raster images for SVGs, which also allows easy customization of icon colors (#68, #97).
- Added optional onPress to toast, which currently breaks the ability to swipe to dismiss, but only if onPress is provided (#86).

I encourage you to check out the [documentation](https://github.com/StratusCode/react-native-toast-hook#usage) to see how the API has changed.

The [first commit](https://github.com/StratusCode/react-native-toast-hook/commit/9ecece98f06327d4278a56293ad05fcbf253fa35) was mostly a straight typescript conversion, which you might find useful. You are of course welcome to backport anything else you'd like as well, but you won't want the whole fork as a PR as it is very opinionated toward my company's code style and infrastructure.

**Comment by calintamas** [comment]
@caleb-harrelson nice! I added the `onPress` as well, with a slightly different api

**Comment by caleb-harrelson** [comment]
I like it. Looks like you solved the collisions with swipe to dismiss too, awesome!
