### ISSUE TITLE
Is there a way to make this animate from beneath a react-navigation tab bar?

### ISSUE THREAD

**Issue by pdugan20** [calintamas/react-native-toast-message#88]
Is there a way that I can get this to animate from beneath the react-navigation tab bar instead of animate in over the top of it? I can get it to render from behind by passing it in on individual screens rather than up at my AppNavigator, but then I lose the ability to call it from different stacks within the TabNavigator.

**Comment by pdugan20** [comment]
![Nov-23-2020 13-03-03](https://user-images.githubusercontent.com/1837100/100015136-533b5200-2d8c-11eb-950d-51f158e8b2ed.gif)

Here's an example. So if I render the toast down inside the "Home" stack, it animates from beneath the bottom tab bar, but I can't access it inside any of the other stacks. However, if I render it in my AppNavigator, I can access it from any stack but then it always animates over the top of the bottom tab bar.

**Comment by pdugan20** [comment]
I was able to solve for this by rendering the Toast component conditionally at the top of each Stack.Navigator based on whichever stack was focused at a given time. A little inelegant, but seems to be working fine.

**Comment by calintamas** [comment]
Glad you found a way! Honestly, I'm not sure if there's any alternative

**Comment by pdugan20** [comment]
Thanks for the response! I'll go ahead and close.
