### ISSUE TITLE
null is not an object (evaluating 'this._ref.show')

### ISSUE THREAD

**Issue by rogerkerse** [calintamas/react-native-toast-message#89]
After npm installing this library, the given code doesn't work.

`<Toast ref={Toast.setRef} />`

and after initialisation calling `Toast.show({ text1: "Hello" })` // error thrown.

I also added a log into setRef to see if it gets the reference, it does, but calling getRef() after it returns null.
There was a suggested solution of using yarn instead of npm, but that is not an option since npm is way more popular (https://github.com/calintamas/react-native-toast-message/issues/82).

**Comment by rogerkerse** [comment]
I created pull request for it https://github.com/calintamas/react-native-toast-message/pull/90

**Comment by calintamas** [comment]
Thank you @rogerkerse. 
Published in [v1.3.5](https://github.com/calintamas/react-native-toast-message/releases/tag/v1.3.5)
