### ISSUE TITLE
Change default toast settings

### ISSUE THREAD

**Issue by matheuscastroweb** [calintamas/react-native-toast-message#98]
In the `topOffset` parameter I needed to add `getStatusBarHeight()` + `value` to all my `Toast.show` to work on other devices correctly.

Adding this type of configuration to your instance would be nice.

`<Toast ref={(ref) => Toast.setRef(ref)} />` on here.

From what I read the config does not satisfy this request, just to create new toasts.

**Comment by calintamas** [comment]
I agree. I'll add `topOffset` and `bottomOffset` as props in the next version.
Thanks for your suggestion!
